### ISSUE TITLE
How can i use Snappydata work with CDH's spark

### ISSUE THREAD

**Issue by lichar-cheng** [SnappyDataInc/snappydata#1023]
We're using CDH Parces installed 2.1.0.cloudera2-1,
using snappydata-1.0.1 smart connect with this version of spark , will the table not found,like this:

org.apache.spark.sql.TableNotFoundException: Table 'NEWAPP.AGGRADIMPRESSIONS1' not found;
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog.lookupRelation(SnappyStoreHiveCatalog.scala:514)
  at org.apache.spark.sql.SmartConnectorHelper.createTable(SmartConnectorHelper.scala:125)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:1046)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:1011)
  at org.apache.spark.sql.execution.CreateMetastoreTableUsing.run(ddl.scala:43)

it's work on spark-2.1.1 , 

can i use SD connect spark-2.1.0.cloudera2-1? how?

thanks~

**Comment by sumwale** [comment]
@lichar-cheng Unfortunately Spark broke SparkSession API compatibility between 2.1.0 and 2.1.1 causing issues with SnappySession between the two minor revisions. We had made changes to restore source-level compatibility so that if the 1.0.1 product is built against 2.1.0 then it should work with CDH based on Spark 2.1.0.

**Comment by lichar-cheng** [comment]
So I should not download it directly from https://github.com/SnappyDataInc/snappydata/releases/ , but to follow this https://github.com/SnappyDataInc/snappydata/blob/master/docs/install/building_from_source.md  to build?

**Comment by sumwale** [comment]
@lichar-cheng Right, if you are using OSS release then you will need:

git clone https://github.com/SnappyDataInc/snappydata.git -b v1.0.1 --recursive

Then inside snappydata directory change the "sparkVersion" in build.gradle and store/build.gradle to 2.1.0 from 2.1.1

Then:

./gradlew distProduct

This will create the packages in build-artifacts/scala-2.11/distributions (or extracted product in build-artifacts/scala-2.11/snappy).

**Comment by sumwale** [comment]
@lichar-cheng If the build is stuck for long time in "Resolving dependencies ':snappy-cluster_2.11:testRuntimeClasspath'" please comment out repository.snappydata.io in build.gradle which is no longer used and is offline:

```
diff --git a/build.gradle b/build.gradle
index 164171f..f153aa9 100644
--- a/build.gradle
+++ b/build.gradle
@@ -58,8 +58,8 @@ allprojects {
     maven { url 'https://dl.bintray.com/big-data/maven' }
     maven { url "https://repo.spring.io/libs-release" }
     maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
-    maven { url 'http://repository.snappydata.io/repository/internal' }
-    maven { url 'http://repository.snappydata.io/repository/snapshots' }
+    // maven { url 'http://repository.snappydata.io/repository/internal' }
+    // maven { url 'http://repository.snappydata.io/repository/snapshots' }
     maven { url 'https://app.camunda.com/nexus/content/repositories/public' }
   }
```

**Comment by lichar-cheng** [comment]
@sumwale 
i try many times，but don‘t work
use ./gradlew show：: No such file or directory；
so i use  ‘gradle wrapper ’ to make ./gradlew work,but show:A base directory must be specified in the task or via a method argument!

![20a3fd2d-ed77-4924-bfc2-a8fd2b4041b9](https://user-images.githubusercontent.com/35256099/40046748-4e299474-5860-11e8-8cf1-f0db7e40d1f9.png)

---------
this is build.gradle line,but i don't know how to mkdir a directory
![image](https://user-images.githubusercontent.com/35256099/40046770-5880a732-5860-11e8-8429-4cf503f3b187.png)

**Comment by lichar-cheng** [comment]
hi @sumwale  i got Last question，because i forget change store/build.gradle 

but  when i change,it's still wrong:
![image](https://user-images.githubusercontent.com/35256099/40405558-af0d8b30-5e8f-11e8-9d7c-96224376ad70.png)

it's work when sparkVersion is 2.1.1 ,but don't work when i change to 2.1.0

i can't download the project from git,so  download project module by myself ,show :
![image](https://user-images.githubusercontent.com/35256099/40405574-cacf93b8-5e8f-11e8-9a62-9dd44fb85cd3.png)

**Comment by caiyt** [comment]
I have the same problem

[pgxl@lx33 snappydata]$ ./gradlew Product

FAILURE: Build failed with an exception.

* Where:
Build file '/home/pgxl/soft/snappydata/build.gradle' line: 380

* What went wrong:
A problem occurred evaluating root project 'snappydata_2.11'.
> A base directory must be specified in the task or via a method argument!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
