### ISSUE TITLE
Thrift class conflict error with existing spark installation

### ISSUE THREAD

**Issue by jessyZu** [SnappyDataInc/snappydata#1076]
my dependency:
        <spark.version>2.1.1</spark.version>
        <dependency>
            <groupId>io.snappydata</groupId>
            <artifactId>snappydata-store-client</artifactId>
            <version>1.6.1</version>
        </dependency>

I used spark to insert data into snappy by JDBC client.
After resolver the dependency, there is only one version of thrift : libthrift-0.9.3.
And the field org.apache.thrift.protocol.TCompactProtocol.i32buf  is not private.
It's a very strange exception!

`Java exception: 'tried to access field org.apache.thrift.protocol.TCompactProtocol.i32buf from class org.apache.thrift.protocol.Helper: class java.lang.IllegalAccessError'.
	at io.snappydata.thrift.common.ThriftExceptionUtil.newSnappyException(ThriftExceptionUtil.java:164)
	at io.snappydata.thrift.internal.ClientService.handleException(ClientService.java:682)
	at io.snappydata.thrift.internal.ClientService.prepareStatement(ClientService.java:1031)
	at io.snappydata.thrift.internal.ClientPreparedStatement.prepare(ClientPreparedStatement.java:126)
	at io.snappydata.thrift.internal.ClientPreparedStatement.<init>(ClientPreparedStatement.java:79)
	at io.snappydata.thrift.internal.ClientConnection.prepareStatement(ClientConnection.java:182)
	at io.snappydata.thrift.internal.ClientConnection.prepareStatement(ClientConnection.java:63)
	at com.enniu.dataimport.snappy.SnappyHelper$.importHiveData2Snappy(SnappyHelper.scala:64)
	at com.enniu.dataimport.snappy.SnappyHelper$.main(SnappyHelper.scala:32)
	at com.enniu.dataimport.snappy.SnappyHelper.main(SnappyHelper.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.IllegalAccessError: tried to access field org.apache.thrift.protocol.TCompactProtocol.i32buf from class org.apache.thrift.protocol.Helper
	at org.apache.thrift.protocol.Helper.getI32Buffer(Helper.java:27)`

**Comment by jessyZu** [comment]
The jvm considers classes loaded from different classloaders to be in different "runtime packages", even if they have the same package name. Quoting from the jvm spceification, section 5.3:
