### ISSUE TITLE
snappydata 1.0.1 smart connect mode support spark2.2.0?

### ISSUE THREAD

**Issue by zj619** [SnappyDataInc/snappydata#1121]
I use smart connect mode with "spark-submit --master yarn--conf spark.snappy.connection=10.5.3.113:1527 --jars /disk1/snappy-lib/activation-1.1.1.jar,..., --class com.test.snappy.JavaSmartConnectorExample SnappyStudy.jar",wile I get 
18/08/08 22:24:57 INFO security.HadoopFSCredentialProvider: Renewal interval is 86400056 for token HDFS_DELEGATION_TOKEN
Exception in thread "main" java.lang.AbstractMethodError
	at org.apache.spark.deploy.yarn.security.ConfigurableCredentialManager$$anonfun$obtainCredentials$2.apply(ConfigurableCredentialManager.scala:81)
	at org.apache.spark.deploy.yarn.security.ConfigurableCredentialManager$$anonfun$obtainCredentials$2.apply(ConfigurableCredentialManager.scala:80)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.apache.spark.deploy.yarn.security.ConfigurableCredentialManager.obtainCredentials(ConfigurableCredentialManager.scala:80)
	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:408)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:856)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:172)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:56)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:165)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:512)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2511)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:909)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:901)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:901)
	at com.iflytek.snappy.JavaSmartConnectorExample.main(JavaSmartConnectorExample.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/08/08 22:24:58 INFO storage.DiskBlockManager: Shutdown hook called
.I search on the internet,it seems to be a version problem, hope someone can answer my question, thanks a lot!

**Comment by jramnara** [comment]
Which Spark distribution are you using ? and version ? 
I would also use 'spark.snappydata.connection' as the conf property to connect to snappydata. Finally, looks like you are specifying all the SnappyData jars explicitly in your 'jars' conf. Why ?  Use '--packages' option as mentioned here - https://snappydatainc.github.io/snappydata/howto/spark_installation_using_smart_connector/

**Comment by zj619** [comment]
Hi, I am now using apache spark 2.2.0, the reason why I do not use "--packages" is that my machines can not connect to the internet, I can only use "--jars' to pass my additional jars.
