### ISSUE TITLE
No suitable driver found for jdbc:snappydata:

### ISSUE THREAD

**Issue by vipinmehargithub** [SnappyDataInc/snappydata#1244]

**Comment by vipinmehargithub** [comment]
Unable to connect using jaydebeapi 
>>> conn = jaydebeapi.connect('io.snappydata.jdbc.ClientDriver', ['jdbc:snappydata://localhost:1527;SHOWPLAN=ON'],'opt/snappydata-jdbc_2.11-1.0.2.1.jar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/jaydebeapi/__init__.py", line 68, in connect
    connection = gateway.jvm.DriverManager.getConnection(*driver_args)
  File "/usr/local/lib/python3.5/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.5/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:java.sql.DriverManager.getConnection.
: java.sql.SQLException: No suitable driver found for jdbc:snappydata://localhost:1527;SHOWPLAN=ON
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
