### ISSUE TITLE
CREATE HDFSSTORE results in ClassNotFoundException for BlockCache

### ISSUE THREAD

**Issue by willschipp** [SnappyDataInc/snappydata#194]
When executing the following statement;

`create hdfsstore sandbox namenode 'hdfs://sandbox.hortonworks.com:8020';`

It returns the following:

```
ERROR X0Z30: SQLSTATE=X0Z30,SEVERITY=-1: (Server=localhost.localdomain[1528],Thread[DRDAConnThread_31,5,gemfirexd.daemons]) An error was received from HDFS while performing 'org/apache/hadoop/hbase/io/hfile/BlockCache'.
```

In the logs there is this;

```
16/03/15 07:25:06.048 UTC DRDAConnThread_31<tid=0x91> INFO snappystore:
[TRACE 2016/03/15 07:25:06.048 UTC GFXD:TRACE <DRDAConnThread_31> tid=0x91] (XID = 436(nestedUpdateUserTransaction)@230a8cc1;txState=null;supportsTX=false), (SESSIONID = 15), (DATABASE = snappydata), (DRDAID = NF000001.O163-652176063011919053{  5  }), Failed Statement is: create hdfsstore sandbox namenode 'hdfs://sandbox.hortonworks.com:8020'
ERROR X0Z30: An error was received from HDFS while performing 'org/apache/hadoop/hbase/io/hfile/BlockCache'.
        at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
        at com.pivotal.gemfirexd.internal.engine.access.operations.HDFSStoreCreateOperation.doMe(HDFSStoreCreateOperation.java:98)
        at com.pivotal.gemfirexd.internal.engine.raw.log.MemLogger.logAndDo(MemLogger.java:121)
        at com.pivotal.gemfirexd.internal.engine.access.GemFireTransaction.logAndDo(GemFireTransaction.java:1340)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.CreateHDFSStoreConstantAction.executeConstantAction(CreateHDFSStoreConstantAction.java:76)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:64)
        at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:593)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2132)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1277)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1000)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:499)
        at com.pivotal.gemfirexd.internal.impl.drda.DRDAConnThread.parseEXCSQLIMM(DRDAConnThread.java:6552)
        at com.pivotal.gemfirexd.internal.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:894)
        at com.pivotal.gemfirexd.internal.impl.drda.DRDAConnThread.run(DRDAConnThread.java:374)
============= begin nested exception, level (1) ===========
java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/io/hfile/BlockCache
        at com.gemstone.gemfire.cache.hdfs.internal.HDFSStoreFactoryImpl.create(HDFSStoreFactoryImpl.java:65)
        at com.pivotal.gemfirexd.internal.engine.access.operations.HDFSStoreCreateOperation.doMe(HDFSStoreCreateOperation.java:92)
        ... 12 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
java.lang.ClassNotFoundException: org.apache.hadoop.hbase.io.hfile.BlockCache
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 14 more
============= end nested exception, level (2) ===========
```

Environment:  vanilla install of `0.2.0-PREVIEW` on Hortonworks Sandbox VM 2.3

**Comment by hbhanawat** [comment]
The error you are seeing here is because with GemXD (snappy-store), creation of HDFS Store needed slightly modified version of HFile implementation of HBase. This was shipped as a separate jar. 

With SnappyData we are not supporting create hdfsstore ddls and hence this jar is not shipped. You can use  spark way of interacting with HDFS.

**Comment by sumwale** [comment]
Reopening since HDFS support is still there in the product (for existing users).

**Comment by sumwale** [comment]
The hbase jar has to be included in the spark classpath explicitly. I have updated the docs accordingly in d1e066304a6e7ad69ad63f18900a7f78f1661df5

Add to conf/spark-env.sh: export SPARK_DIST_CLASSPATH=/path/to/hbase-0.94.27.jar

Newer builds will include the hbase jar separately in the product tree (18b76a0cf0ca480d07cef1b97ee98d21df348576) but for older builds download hbase 0.94 version from maven (like here http://mvnrepository.com/artifact/org.apache.hbase/hbase/0.94.27) or from project site. Note that all other dependencies of hbase are already in product jars so you should not need the full package as from project site and just the jar from maven central will suffice.

Spark has an indirect dependency on hbase which depends on a somewhat incompatible 0.98 version, so right now it is not possible to use both of GemFireXD's HDFS and Spark hbase support together. This is being tracked and will be fixed in next release with hbase included in the product assembly jar itself so no additional setting will be required then.

**Comment by sumwale** [comment]
@willschipp if you get a chance, please do tell if the settings mentioned in the previous comment work for you.

**Comment by willschipp** [comment]
@sumwale - have checked and verified that the CREATE HDFSSTORE statement works after following the instructions above with 0.2.0-PREVIEW binary

**Comment by sumwale** [comment]
@willschipp Thanks. PR is now open that upgrades the hbase version to 0.98.x to be consistent with Spark's version and thus allows packaging it in the product assembly jar: https://github.com/SnappyDataInc/snappy-store/pull/37

**Comment by adnanfaizan** [comment]
after adding hbase-server-0.98.17-hadoop2.jar as mentioned above, now exception is coming to add jar for  'org/apache/hadoop/hbase/io/HeapSize'.
This class is present in hbase-common-0.98.17-hadoop2.jar. Does that mean we need to add multiple jars to the path?

**Comment by sumwale** [comment]
@adnanfaizan This should not be required any more since it is now included in snappy-store. Let me check.

**Comment by sumwale** [comment]
@adnanfaizan Can you tell which release you are trying with (or custom build revision)? I can see the hbase jars being included snappydata-assembly jar in 0.3 preview release and master builds (though haven't checked CREATE HDFSSTORE yet).

**Comment by adnanfaizan** [comment]
I am using - snappydata-0.2.1-PREVIEW-bin.

I have tried several way of putting path for both jar using comma, semi colon but nothing worked. Putting semi colon makes this line inaccessible. putting comma let me start the snappy but doesn't pick the jar. Can you help me setting correct path? Example I musing with comma as below -

export SPARK_DIST_CLASSPATH=/path/hbase-server-0.98.17-hadoop2.jar,/path/hbase-common-0.98.17-hadoop2.jar

I also tried (but no luck) -
export SPARK_DIST_CLASSPATH=$(find /path/ -name *.jar | tr "\n" ";")

**Comment by sumwale** [comment]
@adnanfaizan Please use 0.3 release. It includes hbase and all dependencies, and no additional setting is required.

**Comment by adnanfaizan** [comment]
Thanks for prompt responses..
I got jars from http://www.snappydata.io/download and it has only 0.2.
Where to download 0.3?

**Comment by sumwale** [comment]
Please take from github releases: https://github.com/SnappyDataInc/snappydata/releases

Will send a note to add to snappydata downloads page too.
