### ISSUE TITLE
java.util.NoSuchElementException: key not found: path -- when writing new table

### ISSUE THREAD

**Issue by saifellafi** [SnappyDataInc/snappydata#205]
Testing in a spark-shell, I can successfully create tables, insertIntoTable and create from External succesfully, however, when loading an existing table and trying to write it using DataFrameWriter, I get such error, and no table is created.

z.write.mode("overwrite").saveAsTable("new_table")

...

16/03/21 16:43:09 INFO metastore.HiveMetaStore: 1: get_table : db=default tbl=NEW_TABLE
16/03/21 16:43:09 INFO HiveMetaStore.audit: ugi=cmor    ip=unknown-ip-addr      cmd=get_table : db=default tbl=NEW_TABLE
java.util.NoSuchElementException: key not found: path
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at org.apache.spark.sql.execution.datasources.CaseInsensitiveMap.default(ddl.scala:150)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at org.apache.spark.sql.execution.datasources.CaseInsensitiveMap.apply(ddl.scala:150)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:223)
        at org.apache.spark.sql.SnappyContext.createTable(SnappyContext.scala:542)
        at org.apache.spark.sql.CreateMetastoreTableUsingSelect.run(snappyParsers.scala:402)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:138)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:136)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:136)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:230)
        at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:200)
        at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:26)

**Comment by hbhanawat** [comment]
You are trying to write a table without specifying the format i.e. underlying output data source. So it assumes the default data source which is "parquet"  and asks for the parquet folder path. 

If you want to write in snappy-store's table, use either one of these two commands based on your requirement: 
   // Your output data source is a column table in snappy store 
    df.write.format("column").mode("overwrite").saveAsTable("airline")
   // Your output data source is a row table in snappy store 
    df.write.format("row").mode("overwrite").saveAsTable("airline")

If you want to append into this table, you can use df.write.insertInto command.

**Comment by saifellafi** [comment]
Appreciated, thank you

**Comment by saifellafi** [comment]
The confusion came from the example from: https://github.com/SnappyDataInc/snappydata/blob/master/snappy-examples/src/main/scala/io/snappydata/examples/CreateAndLoadAirlineDataJob.scala

snc.table(colTable).write.mode(SaveMode.Append).saveAsTable(sampleTable)

Where such format was not specified, i am not completely sure where it is inferred from in such case.

**Comment by sumwale** [comment]
@saifellafi The format is not required when using SaveMode.Append into an existing table since it is assumed to exist and the format/options of the target table are used. However, when using the Overwrite mode, the format is required (and also any required options that may have been provided in original create table) because the table will be created afresh.

**Comment by sumwale** [comment]
@saifellafi To clarify "table will be created afresh": snappydata data sources "column", "row", "sample", "topK" all truncate the existing table and do not create new table so it is fine to skip options for these. Other Spark data sources may drop/recreate the table, so it is safer to provide any required options for other data sources unless their behaviour w.r.t. overwrite is specifically known.
