### ISSUE TITLE
Issue with loading external jars during batch job execution

### ISSUE THREAD

**Issue by Madhavii** [SnappyDataInc/snappydata#386]
We are trying out snappydata for one of our project and we have a requirement to load jar @ runtime and instantiate a class for executing a Map Function. The jar location is set using 'dependent-uris' attribute in the Spark JobServer while triggering the Job. I can see that the jar is copied to the work folder in the 'server' node. But during the execution, it is throwing classnotfound exception. Note that these jars are not bundled with the actual 'job' jar.  Any pointers to solve the issue is highly appreciated.

thanks in advance.

Cluster setup
- node 1 -> Locator + lead
- node2 -> Server
- Snappy version = 0.6 RC
## \- OS - Linux

 java.lang.Exception: Unable To Instantiate  BKM Function : com.company.SomeRuleClass And The Reason Is com.company.SomeRuleClass
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.pivotal.gemfirexd.internal.impl.services.reflect.JarLoader.loadClass(JarLoader.java:296)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)

Madhavi

**Comment by nthanvi** [comment]
The 0.6 release of snappy does not fully support the jar loaded through the 'dependent-uris' attribute. This is a work in progress and you can expect the full integration in next release. 
As a workaround you can  install the jar from the server node (node2)  through the following command.

bin/snappy-shell install-jar  -name SomeIdentifierForTheJar  -file JarLocation   -client-bind-address locatorHostName  -client-port LocatorClientPort[1527]

**Comment by sumwale** [comment]
Jar loading in snappydata is supported in two ways: a) using [system procedures](https://snappydatainc.github.io/snappydata/programming_guide/#managing-jar-files), b) specified in a [job](https://snappydatainc.github.io/snappydata/programming_guide/#submitting-jobs). The "dependent-uris" mechanism of job-server also should be working now, so closing.
