### ISSUE TITLE
AnalysisException: Option 'url' not specified for cluster yarn

### ISSUE THREAD

**Issue by hzxjtx** [SnappyDataInc/snappydata#511]
hi
  i am a newer of snappydata. I use spark-2.0.2 shell on yarn model,  when i use snappy to create table,  i get some error like this:
scala>  snappy.createTable("COLUMN_TABLE", "column", df.schema, props)
org.apache.spark.sql.AnalysisException: Option 'url' not specified for cluster yarn;
  at org.apache.spark.sql.execution.columnar.ExternalStoreUtils$.defaultStoreURL(ExternalStoreUtils.scala:167)
  at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider$$anonfun$11.apply(JDBCAppendableRelation.scala:386)
  at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider$$anonfun$11.apply(JDBCAppendableRelation.scala:386)
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
  at org.apache.spark.sql.execution.datasources.CaseInsensitiveMap.getOrElse(ddl.scala:112)
  at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.getRelation(JDBCAppendableRelation.scala:385)
  at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.createRelation(JDBCAppendableRelation.scala:359)
  at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.createRelation(JDBCAppendableRelation.scala:315)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:343)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:930)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:719)

   can somebody give me some information

**Comment by SachinJanani** [comment]
Hi hzxjtx,
Can you please share the command (along with the options) you are using for starting the spark-shell?

**Comment by hzxjtx** [comment]
hi, @SachinJanani , thanks for your attention.

Yesterday I run spark-shell just as follows:

import snappy.implicits._
val snappy = new org.apache.spark.sql.SnappySession(spark.sparkContext)
val props = Map("BUCKETS" -> "2")
case class Data(COL1: Int, COL2: Int, COL3: Int)

 val data = Seq(Seq(1, 2, 3), Seq(7, 8, 9), Seq(9, 2, 3), Seq(4, 2, 3), Seq(5, 6, 7))
 val rdd = spark.sparkContext.parallelize(data, data.length).map(s => new Data(s(0), s(1), s(2)))

 val df = snappy.createDataFrame(rdd)

 // create a column table
 snappy.dropTable("COLUMN_TABLE", ifExists = true)

 // "column" is the table format (that is row or column)
 // dataDF.schema provides the schema for table
 snappy.createTable("COLUMN_TABLE", "column", df.schema, props)

then I get the above errors, thanks

**Comment by hzxjtx** [comment]
hi, @SachinJanani 
today i use the snappy multi hosts model to run spark-shell on yarn（./bin/spark-shell --conf spark.snappydata.store.sys-disk-dir=quickstartdatadir --conf spark.snappydata.store.log-file=quickstartdatadir/quickstart.log --packages "
SnappyDataInc:snappydata:0.7-s_2.11" --master yarn --conf snappydata.store.locators=192.168.1.85:10334）
 and the props set as follows

val props = Map("BUCKETS" -> "2", "url" -> "jdbc:snappydata://192.168.1.85:10334")
and other operation is the same, but when i createTable, i get errors as follows:
2017-02-14 15:36:29,020 ERROR [main] pool.ConnectionPool: Unable to create initial connections of pool.
java.sql.SQLNonTransientConnectionException: (SQLState=08006 Severity=40000) A communications error has been detected: Failed after trying all available servers: [], for control URL: 192.168.1.85[10334].
        at com.pivotal.gemfirexd.internal.shared.common.error.DefaultExceptionFactory40.getSQLException(DefaultExceptionFactory40.java:85)
        at com.pivotal.gemfirexd.internal.shared.common.error.ExceptionUtil.newSQLException(ExceptionUtil.java:148)
        at com.pivotal.gemfirexd.internal.client.am.SqlException.getSQLException(SqlException.java:419)
        at com.pivotal.gemfirexd.internal.client.net.NetConnection.getPreferredServer(NetConnection.java:1625)
        at com.pivotal.gemfirexd.internal.client.net.NetConnection.preConnect(NetConnection.java:1973)
        at com.pivotal.gemfirexd.internal.client.net.NetConnection.newAgent_(NetConnection.java:2479)
        at com.pivotal.gemfirexd.internal.client.am.Connection.<init>(Connection.java:656)
        at com.pivotal.gemfirexd.internal.client.net.NetConnection.<init>(NetConnection.java:263)
        at com.pivotal.gemfirexd.internal.client.net.NetConnection40.<init>(NetConnection40.java:86)
        at com.pivotal.gemfirexd.internal.client.net.ClientJDBCObjectFactoryImpl40.newNetConnection(ClientJDBCObjectFactoryImpl40.java:305)
        at com.pivotal.gemfirexd.jdbc.ClientDRDADriver.connect(ClientDRDADriver.java:222)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:716)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
        at org.apache.spark.sql.execution.ConnectionPool$.getPoolConnection(ConnectionPool.scala:137)
        at org.apache.spark.sql.execution.columnar.JDBCSourceAsStore.getConnection(JDBCSourceAsStore.scala:110)
        at org.apache.spark.sql.execution.columnar.ExternalStore$$anonfun$1.apply(ExternalStore.scala:49)
        at org.apache.spark.sql.execution.columnar.ExternalStore$$anonfun$1.apply(ExternalStore.scala:49)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.execution.columnar.ExternalStore$class.tryExecute(ExternalStore.scala:49)
        at org.apache.spark.sql.execution.columnar.JDBCSourceAsStore.tryExecute(JDBCSourceAsStore.scala:43)
        at org.apache.spark.sql.execution.columnar.JDBCAppendableRelation.<init>(JDBCAppendableRelation.scala:73)
        at org.apache.spark.sql.execution.columnar.impl.BaseColumnFormatRelation.<init>(ColumnFormatRelation.scala:74)
        at org.apache.spark.sql.execution.columnar.impl.ColumnFormatRelation.<init>(ColumnFormatRelation.scala:443)
        at org.apache.spark.sql.execution.columnar.impl.DefaultSource.createRelation(ColumnFormatRelation.scala:723)
        at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.createRelation(JDBCAppendableRelation.scala:360)
        at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.createRelation(JDBCAppendableRelation.scala:315)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:343)

**Comment by SachinJanani** [comment]
Hi @hzxjtx 
The way for specifying locator property through spark-shell is "**_spark.snappydata.store.locators_**" can please you try changing the name of this property.So the command should look as follows:
```
./bin/spark-shell --conf spark.snappydata.store.sys-disk-dir=quickstartdatadir --conf spark.snappydata.store.log-file=quickstartdatadir/quickstart.log --packages "SnappyDataInc:snappydata:0.7-s_2.11" --master yarn --conf spark.snappydata.store.locators=192.168.1.85:10334
```
_Note: Assuming your locator is running on 192.168.1.85_

**Comment by hzxjtx** [comment]
it works, thanks @SachinJanani

**Comment by hzxjtx** [comment]
it seam works!
but i still get some error:
2017-02-15 10:28:21,977 ERROR [main] pool.ConnectionPool: Unable to create initial connections of pool.
java.sql.SQLNonTransientConnectionException: (SQLState=08006 Severity=40000) A communications error has been detected: Failed after trying all available servers: [dserver5[1527], localhost[1527]], for control hos
t[port]: dserver5[1527].
        at com.pivotal.gemfirexd.internal.shared.common.error.DefaultExceptionFactory40.getSQLException(DefaultExceptionFactory40.java:85)
        at com.pivotal.gemfirexd.internal.shared.common.error.ExceptionUtil.newSQLException(ExceptionUtil.java:148)

**Comment by sumwale** [comment]
@hzxjtx the last error usually means that no servers were available in the snappydata cluster, or lost connection with the locator. Can you try with the latest 0.8 release and see if this is still an issue?

**Comment by sumwale** [comment]
@hzxjtx Closing this issue in absence of further information. Please try with latest release (the final 1.0 release will be out this week) and see if an issue is still seen. The property name for smart connector mode is now "spark.snappydata.connection=locator-host:locator-client-port" and uses the thin client host:port to connect (not the peer port).
