### ISSUE TITLE
Column table use PERSISTEN and  EVICTION_BY throw exceptions

### ISSUE THREAD

**Issue by hzxjtx** [SnappyDataInc/snappydata#518]
hi
 In my use case, the total data size is bigger than all dataserver nodes memory size. so when create column table, i use the option as follows:
   Map(("PARTITION_BY" -> "o_orderkey"), ("BUCKETS" -> buckets), ("PERSISTENT" -> "ASYNCHRONOUS"), ("EVICTION_BY" -> "LRUHEAPPERCENT 50"), ("OFFHEAP" -> "true"))

   but i get execption as follows:
17/03/02 14:27:46 ERROR jobserver.JobManagerActor: Got NonFatal Exception:
java.sql.SQLSyntaxErrorException(42X01): Syntax error: Encountered "50" at line 1, column 448.
Was expecting one of:
    <EOF>
    ...
    "buckets" ...
    "evictaction" ...
    "eviction" ...
    "expire" ...
    "initsize" ...
    "local" ...
    "maxpartsize" ...
    "partition" ...
    .
        at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:463)
        at com.pivotal.gemfirexd.internal.impl.sql.compile.ParserImpl.parseStatement(ParserImpl.java:231)
        at com.pivotal.gemfirexd.internal.impl.sql.GenericStatement.prepMinion(GenericStatement.java:598)
        at com.pivotal.gemfirexd.internal.impl.sql.GenericStatement.prepare(GenericStatement.java:219)
        at com.pivotal.gemfirexd.internal.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(GenericLanguageConnectionContext.java:1010)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1205)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:502)
        at org.apache.spark.sql.sources.JdbcExtendedUtils$.executeUpdate(jdbcExtensions.scala:87)
        at org.apache.spark.sql.execution.columnar.impl.BaseColumnFormatRelation.createActualTable(ColumnFormatRelation.scala:375)
        at org.apache.spark.sql.execution.columnar.impl.BaseColumnFormatRelation.createTable(ColumnFormatRelation.scala:329)
        at org.apache.spark.sql.execution.columnar.impl.DefaultSource.createRelation(ColumnFormatRelation.scala:740)
        at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.createRelation(JDBCAppendableRelation.scala:376)
        at org.apache.spark.sql.execution.columnar.ColumnarRelationProvider.createRelation(JDBCAppendableRelation.scala:324)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:343)
        at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:932)
        at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:721)
        at org.apache.spark.sql.SnappyContext.createTable(SnappyContext.scala:397)
        at io.snappydata.benchmark.TPCHColumnPartitionedTable$.createAndPopulateOrderTable(TPCHColumnPartitionedTable.scala:147)
        at io.snappydata.benchmark.snappy.TPCH_Snappy_Tables$.runSnappyJob(TPCH_Snappy_Tables.scala:75)
        at org.apache.spark.sql.SnappySQLJob$class.runJob(SnappySessionFactory.scala:75)
        at io.snappydata.benchmark.snappy.TPCH_Snappy_Tables$.runJob(TPCH_Snappy_Tables.scala:26)
        at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:315)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
17/03/02 14:27:46 ERROR jobserver.JobManagerActor: Exception from job c7e36e19-6b94-40bb-9293-fce9bcfb4676:

can somebody give me some notice? thanks

**Comment by rishitesh** [comment]
Can you please send the complete DDL ? Also as a note,  we don't support
 OFFHEAP feature yet for column tables.

Regards,
Rishitesh Mishra,
SnappyData . (http://www.snappydata.io/)

https://in.linkedin.com/in/rishiteshmishra

**Comment by rishitesh** [comment]
Also you can not specify any value for LRUHEAPPERCENT.  This percent is
determined by *-eviction-heap-percentage* boot parameter. The default value
is 81 percent of heap.

Regards,
Rishitesh Mishra,
SnappyData . (http://www.snappydata.io/)

https://in.linkedin.com/in/rishiteshmishra

**Comment by hzxjtx** [comment]
@rishitesh 

thanks for your help. this is tpch benchmark(cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala), the cluster memory is less than data size.

the code as follows:

      val p1 = Map(("PARTITION_BY" -> "o_orderkey"), ("BUCKETS" -> buckets), ("PERSISTENT" -> "ASYNCHRONOUS"))
      val snappyContext = sqlContext.asInstanceOf[SnappyContext]
      snappyContext.createTable("ORDERS", "column", newSchema, p1)
      //orderDF.write.insertInto("ORDERS")
      orderDF.write.format("COLUMN").mode(SaveMode.Append).saveAsTable("ORDERS")

      orderDF.createOrReplaceTempView("ORDERS")
      sqlContext.cacheTable("ORDERS")
      sqlContext.table("ORDERS").count()

I want snappydata can evict the extra data to disk, not just only use memory

**Comment by rishitesh** [comment]
Yes , you can add ( "EVICTION_BY" -> "LRUHEAPPERCENT") as one of option.
Your code was correct apart from the number after LRUHEAPPERCENT.

Regards,
Rishitesh Mishra,
SnappyData . (http://www.snappydata.io/)

https://in.linkedin.com/in/rishiteshmishra

**Comment by hzxjtx** [comment]
@rishitesh 

 sorry, yes it really works, but is there some strategy can works where the data size bigger than the cluster memory size? and i find even set "EVICTION_BY" -> "LRUHEAPPERCENT", dataserver still occur oom errors

**Comment by rishitesh** [comment]
Try to give lower value of eviction percent & critical heap percent.
-critical-heap-percentage ( default 90)
-eviction-heap-percent (default 81)

Both can be set as server startup parameters. Please see
http://snappydatainc.github.io/snappydata/configuration/#example-for-multiple-host-configuration
for how to set startup parameters.


-

Regards,
Rishitesh Mishra,
SnappyData . (http://www.snappydata.io/)

https://in.linkedin.com/in/rishiteshmishra

**Comment by hzxjtx** [comment]
@rishitesh  thanks for your help, it works
