### ISSUE TITLE
Unable to grant privilege on a table to a user

### ISSUE THREAD

**Issue by mp-calebs** [SnappyDataInc/snappydata#650]
We have snappyData 0.8 running with our custom auth-provider. 
The content of gemfirexd.properties is:

gemfirexd.auth-provider=com.xxx.MPUserAuthenticator
mcast-port=0
gemfirexd.sql-authorization=true
gemfirexd.default-recovery-delay=5000
security-peer-auth-init=com.xxx.auth.MPAuthInitialize.create
security-peer-authenticator=com.xxx.auth.MPAuthenticator.create
security-client-auth-init=com.xxx.auth.MPAuthInitialize.create
security-client-authenticator=com.xxx.auth.MPAuthenticator.create

I use snappy/bin/snappy and enter the following to connect to the cluster. s_snappy_admin is also the user used to start all the services of the cluster. 
connect client 'locatorhost:1527;user=s_snappy_admin;password=MyPassword';

With this user, I am able to execute various sql commands except the GRANT like

GRANT SELECT ON das.acs_access_right TO "s-metadata-r";

I found the following error from Snappy Server's log - snappyStore.log

17/06/08 15:27:34.076 CDT TimeScheduler.Thread<tid=0x24> INFO snappystore: MPAuthInitialize.getCredentials: user=s_snappy_admin
17/06/08 15:27:43.894 CDT HiveMetaStore Client-0<tid=0x68> INFO HiveMetaStore: 0: get_table : db=DAS tbl=ACS_ACCESS_RIGHT
17/06/08 15:27:43.895 CDT HiveMetaStore Client-0<tid=0x68> INFO audit: ugi=root ip=unknown-ip-addr      cmd=get_table : db=DAS tbl=ACS_ACCESS_RIGHT
17/06/08 15:27:43.921 CDT HiveMetaStore Client-0<tid=0x68> INFO HiveMetaStore: 0: get_table : db=DAS tbl=ACS_ACCESS_RIGHT
17/06/08 15:27:43.922 CDT HiveMetaStore Client-0<tid=0x68> INFO audit: ugi=root ip=unknown-ip-addr      cmd=get_table : db=DAS tbl=ACS_ACCESS_RIGHT
17/06/08 15:27:43.938 CDT pool-3-thread-5<tid=0xb44> INFO snappystore: TraceDDLReplay: EmbedStatement: Sending DDL statement GRANT SELECT ON das.acs_access_right TO "s-metadata-r"[134] to other VMs in the distributed system for execution: [tx2dcddn020243p(5533)<v0>:30977, tx2dcddn020243p(6037)<v3>:14255, tx2dcddn020443p(22970)<v1>:43309, tx2dcddn020442p(16978)<v5>:8738, tx2dcddn020342p(7128)<v1>:4002, tx2dcddn020342p(8577)<v4>:63432]
17/06/08 15:27:43.949 CDT pool-3-thread-5<tid=0xb44> INFO snappystore: TraceDDLReplay: EmbedStatement: Sending GfxdDDLFinishMessage for DDL statement GRANT SELECT ON das.acs_access_right TO "s-metadata-r"[134] to other VMs in the distributed system for execution: [tx2dcddn020243p(5533)<v0>:30977, tx2dcddn020243p(6037)<v3>:14255, tx2dcddn020443p(22970)<v1>:43309, tx2dcddn020442p(16978)<v5>:8738, tx2dcddn020342p(7128)<v1>:4002, tx2dcddn020342p(8577)<v4>:63432]. This VM is responsible for persisting the statement on HDFS.
17/06/08 15:27:43.954 CDT pool-3-thread-5<tid=0xb44> INFO snappystore:
[TRACE 2017/06/08 15:27:43.954 CDT GFXD:TRACE <pool-3-thread-5> tid=0xb44] (XID = 3055(nestedUpdateUserTransaction)@4f11b5c5;txState=null;supportsTX=false), (SESSIONID = 221), (DATABASE = snappydata), (DRDAID = null), Failed Statement is: null

[TRACE 2017/06/08 15:27:43.954 CDT GFXD:TRACE <pool-3-thread-5> tid=0xb44] ERROR 42506: User 'APP' is not the owner of Table/View 'DAS'.'ACS_ACCESS_RIGHT'.

17/06/08 15:28:27.308 CDT TimeScheduler.Thread<tid=0x24> INFO snappystore: MPAuthInitialize.getCredentials: user=s_snappy_admin
17/06/08 15:29:08.444 CDT TimeScheduler.Thread<tid=0x24> INFO snappystore: MPAuthInitialize.getCredentials: user=s_snappy_admin
17/06/08 15:29:33.746 CDT TimeScheduler.Thread<tid=0x24> INFO snappystore: MPAuthInitialize.getCredentials: user=s_snappy_admin
17/06/08 15:29:35.932 CDT Pooled Waiting Message Processor 122<tid=0xb4d> INFO snappystore: TraceDDLReplay: GfxdDDLMessage@e5e64b0(processorId=16216; processorType=77;posDup=false; connectionID=21474837811; statementID=12884901901; ddl={DDLConflatable [12884901901] SQLText [GRANT SELECT ON das.acs_access_right TO "s-metadata-r"] fullTableName=DAS.ACS_ACCESS_RIGHT;defaultSchema=S_SNAPPY_ADMIN;objectName=null;isCreateTable=false;isDropStatement=false;isAlterTable=false;isAlterTableDropFKConstraint=false;constraintName=null;droppedFKConstraints=null;flags=0x81;additionalFlags=0x0;skipLocalPeek=0;isHDFSPersistent=false;hdfsstoreName=null}) Starting execution
17/06/08 15:29:35.937 CDT Pooled Waiting Message Processor 122<tid=0xb4d> INFO snappystore:
[TRACE 2017/06/08 15:29:35.936 CDT GFXD:TRACE <Pooled Waiting Message Processor 122> tid=0xb4d] (XID = 3075(UserTransaction)@4a60fc0;txState=null;supportsTX=true), (SESSIONID = 222), (DATABASE = snappydata), (DRDAID = null), Failed Statement is: GRANT SELECT ON das.acs_access_right TO "s-metadata-r"

[TRACE 2017/06/08 15:29:35.937 CDT GFXD:TRACE <Pooled Waiting Message Processor 122> tid=0xb4d] ERROR 42506: User 'APP' is not the owner of Table/View 'DAS'.'ACS_ACCESS_RIGHT'.

17/06/08 15:29:35.937 CDT Pooled Waiting Message Processor 122<tid=0xb4d> WARN snappystore: GfxdDDLMessage@e5e64b0(processorId=16216; processorType=77;posDup=false; connectionID=21474837811; statementID=12884901901; ddl={DDLConflatable [12884901901] SQLText [GRANT SELECT ON das.acs_access_right TO "s-metadata-r"] fullTableName=DAS.ACS_ACCESS_RIGHT;defaultSchema=S_SNAPPY_ADMIN;objectName=null;isCreateTable=false;isDropStatement=false;isAlterTable=false;isAlterTableDropFKConstraint=false;constraintName=null;droppedFKConstraints=null;flags=0x81;additionalFlags=0x0;skipLocalPeek=0;isHDFSPersistent=false;hdfsstoreName=null}) SQL exception in executing DDL
java.sql.SQLSyntaxErrorException(42506): User 'APP' is not the owner of Table/View 'DAS'.'ACS_ACCESS_RIGHT'.
        at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:550)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.PrivilegeInfo.checkOwnership(PrivilegeInfo.java:93)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.TablePrivilegeInfo.checkOwnership(TablePrivilegeInfo.java:131)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.TablePrivilegeInfo.executeGrantRevoke(TablePrivilegeInfo.java:237)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.GrantRevokeConstantAction.executeConstantAction(GrantRevokeConstantAction.java:85)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:64)
        at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:593)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2159)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1283)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:971)
        at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.processMessage(GfxdDDLMessage.java:309)
        at com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.basicProcess(GfxdMessage.java:406)
        at com.gemstone.gemfire.internal.cache.AbstractOperationMessage.process(AbstractOperationMessage.java:212)
        at com.gemstone.gemfire.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:429)
        at com.gemstone.gemfire.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.gemstone.gemfire.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:728)
        at com.gemstone.gemfire.distributed.internal.DistributionManager$7$1.run(DistributionManager.java:1089)
        at java.lang.Thread.run(Thread.java:745)

It appears that it failed to get the current user (which is 'S_SNAPPY_ADMIN') and the default user 'APP' is used instead.

**Comment by sumwale** [comment]
@mp-calebs We have yet to integrate the GRANT/REVOKE mechanism of Snappy-store into the Spark side which will be done as part of 1.0 release. For now the GRANT/REVOKE will work properly only in rowstore mode i.e. when everything executes on store side alone and as row tables (setting route-query=false on the connection will allow GRANT/REVOKE to execute and enforce it for all SQL except for DDLs which are always routed to Spark).

**Comment by mp-calebs** [comment]
I'm still getting the same error with route-query=false setting.

/opt/snappy$ ./bin/snappy 
SnappyData version 0.8 
snappy> connect client 'tx2dcddn020443p.tx2.prod.maxpoint.mgt:1527;user=s_snappy_admin;password=Admin#123;route-query=false';
Jun 09, 2017 8:40:24 AM java.util.logging.LogManager$RootLogger log
INFO: Starting client on 'shei1' with ID='93596|2017/06/09 08:40:24.985 CDT' Source-Revision=392bbf24c28530a624b81e1f95232b6da6688e53
Using CONNECTION0
snappy> GRANT SELECT ON das.sec_privilege_type TO "s-metadata-r";
ERROR 42506: (SQLState=42506 Severity=20000) (Server=tx2dcddn020342p/10.3.226.42[1528] Thread=pool-3-thread-10) User 'APP' is not the owner of Table/View 'DAS'.'SEC_PRIVILEGE_TYPE'.
Caused by: ServerException: Server STACK: java.sql.SQLSyntaxErrorException(42506): User 'APP' is not the owner of Table/View 'DAS'.'SEC_PRIVILEGE_TYPE'.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:214)
	at com.pivotal.gemfirexd.internal.engine.Misc.wrapSQLException(Misc.java:1054)
	at com.pivotal.gemfirexd.internal.engine.Misc.wrapRemoteSQLException(Misc.java:1039)
	at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.handleReplyException(GfxdDDLMessage.java:432)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.send(GfxdMessage.java:297)
	at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.send(GfxdDDLMessage.java:132)
	at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.send(GfxdDDLMessage.java:117)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2426)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1283)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:971)
	at io.snappydata.thrift.server.SnappyDataServiceImpl.execute(SnappyDataServiceImpl.java:1656)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1511)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1495)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at io.snappydata.thrift.server.SnappyDataServiceImpl$Processor.process(SnappyDataServiceImpl.java:197)
	at io.snappydata.thrift.server.SnappyThriftServerThreadPool$WorkerProcess.run(SnappyThriftServerThreadPool.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.gemstone.gemfire.distributed.internal.ReplyException: From tx2dcddn020243p(6037)<v3>:14255: Unexpected SQLException on member tx2dcddn020243p(6037)<v3>:14255
	at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.processMessage(GfxdDDLMessage.java:377)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.basicProcess(GfxdMessage.java:406)
	at com.gemstone.gemfire.internal.cache.AbstractOperationMessage.process(AbstractOperationMessage.java:212)
	at com.gemstone.gemfire.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:429)
	at com.gemstone.gemfire.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.gemstone.gemfire.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:728)
	at com.gemstone.gemfire.distributed.internal.DistributionManager$7$1.run(DistributionManager.java:1089)
	... 1 more

Based on the above strace trace, I've found that in 
com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.processMessage at line 288-289 as shown below

      wrapper = GfxdConnectionHolder.getOrCreateWrapper(ddl.getCurrentSchema(),
          this.args.connId, true, null);

where null is used for props (the last arg). Shouldn't it be given a props object with the user property value equal to the login user?

**Comment by sumwale** [comment]
@mp-calebs The wrapper is an internal connection on remote nodes that runs with the privileges of DBA owner so that should not be an issue (see GfxdConnectionWrapper.java:174). This seems to be some issue when sending across the owner of the connection in SnappyData mode with route-query=false. We will fix these issues as well as query routing ones as part of 1.0 release. For now the only case that should work is cluster and clients running in rowstore mode.

If you want to take a look at this further before that and try to figure out the issue, then you are welcome to contribute patches or PRs. Thanks.

**Comment by mp-calebs** [comment]
Passing a property with the current user GfxdConnectionHolder.getOrCreateWrapper doesn't seems to work. It is still complaining that 'APP' is not the owner of the object. 

[TRACE 2017/06/20 12:39:52.951 CDT GFXD:TRACE <Pooled Waiting Message Processor 48> tid=0x20b] ERROR 42506: User 'APP' is not the owner of Table/View 'DAS'.'SEC_PRIVILEGE_TYPE'.

17/06/20 12:39:52.953 CDT Pooled Waiting Message Processor 48<tid=0x20b> WARN snappystore: GfxdDDLMessage@59f6539b(processorId=13319; processorType=77;posDup=false; connectionID=38654705918; statementID=131; ddl={DDLConflatable [131] SQLText [GRANT SELECT ON das.sec_privilege_type TO "s-metadata-r"] fullTableName=DAS.SEC_PRIVILEGE_TYPE;defaultSchema=DAS;objectName=null;isCreateTable=false;isDropStatement=false;isAlterTable=false;isAlterTableDropFKConstraint=false;constraintName=null;droppedFKConstraints=null;flags=0x81;additionalFlags=0x0;skipLocalPeek=0;isHDFSPersistent=false;hdfsstoreName=null}) SQL exception in executing DDL
java.sql.SQLSyntaxErrorException(42506): User 'APP' is not the owner of Table/View 'DAS'.'SEC_PRIVILEGE_TYPE'.
        at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:550)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.PrivilegeInfo.checkOwnership(PrivilegeInfo.java:93)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.TablePrivilegeInfo.checkOwnership(TablePrivilegeInfo.java:131)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.TablePrivilegeInfo.executeGrantRevoke(TablePrivilegeInfo.java:237)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.GrantRevokeConstantAction.executeConstantAction(GrantRevokeConstantAction.java:85)
        at com.pivotal.gemfirexd.internal.impl.sql.execute.MiscResultSet.open(MiscResultSet.java:64)
        at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:593)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2159)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1283)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
        at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:971)
        at com.pivotal.gemfirexd.internal.engine.ddl.GfxdDDLMessage.processMessage(GfxdDDLMessage.java:313)
        at com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.basicProcess(GfxdMessage.java:406)
        at com.gemstone.gemfire.internal.cache.AbstractOperationMessage.process(AbstractOperationMessage.java:221)
        at com.gemstone.gemfire.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:431)
        at com.gemstone.gemfire.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:503)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.gemstone.gemfire.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:730)
        at com.gemstone.gemfire.distributed.internal.DistributionManager$7$1.run(DistributionManager.java:1091)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mp-calebs** [comment]
Finally, I made the following change as a WORKAROUND. Basically, to treat 'APP' as one of the DB admin users. 

PrivilegeInfo.java

protected void checkOwnership( String user,
								   TupleDescriptor objectDescriptor,
								   SchemaDescriptor sd,
								   DataDictionary dd)
		throws StandardException
	{
		// MP_CHANGE_BEGIN
		// ISSUE: https://github.com/SnappyDataInc/snappydata/issues/650
		if("APP".equals(user)) {
			return;
		}
		// MP_CHANGE_END
		if (!user.equals(sd.getAuthorizationId()) &&
				!user.equals(dd.getAuthorizationDatabaseOwner()))
			throw StandardException.newException(SQLState.AUTH_NOT_OWNER,
									  user,
									  objectDescriptor.getDescriptorType(),
									  sd.getSchemaName(),
									  objectDescriptor.getDescriptorName());
	}

And it seems to work. 

17/06/20 14:34:16.785 CDT Pooled Waiting Message Processor 39<tid=0xb3> INFO snappystore: TraceDDLReplay: GfxdDDLMessage@1ca4d631(processorId=14374; processorType=77;posDup=false; connectionID=8589934834; statementID=149; ddl={DDLConflatable [149] SQLText [GRANT SELECT ON das.sec_privilege_type TO "s-metadata-r"] fullTableName=DAS.SEC_PRIVILEGE_TYPE;defaultSchema=DB_SNAPPY_ADMIN;objectName=null;isCreateTable=false;isDropStatement=false;isAlterTable=false;isAlterTableDropFKConstraint=false;constraintName=null;droppedFKConstraints=null;flags=0x81;additionalFlags=0x0;skipLocalPeek=0;isHDFSPersistent=false;hdfsstoreName=null}) Starting execution
17/06/20 14:34:16.889 CDT Pooled Waiting Message Processor 39<tid=0xb3> INFO snappystore: TraceDDLReplay: GfxdDDLFinishMessage@3d2f6488(processorId=14375; processorType=77;posDup=false; connectionID=8589934834; statementID=149; statement={DDLConflatable [149] SQLText [GRANT SELECT ON das.sec_privilege_type TO "s-metadata-r"] fullTableName=DAS.SEC_PRIVILEGE_TYPE;defaultSchema=DB_SNAPPY_ADMIN;objectName=null;isCreateTable=false;isDropStatement=false;isAlterTable=false;isAlterTableDropFKConstraint=false;constraintName=null;droppedFKConstraints=null;flags=0x81;additionalFlags=0x0;skipLocalPeek=0;isHDFSPersistent=false;hdfsstoreName=null}; sequenceId=225; doCommit=true) Successfully committed

**Comment by sumwale** [comment]
@mp-calebs Full support for GRANT/REVOKE and SQL standard compliant security is now available in the enterprise 1.0 RC release (final 1.0 release will be out later this week) so closing this issue.

**Comment by sumwale** [comment]
@mp-calebs As of now GRANT/REVOKE is only available on JDBC/ODBC/thrift connections. Support via Spark APIs will be added shortly.
