### ISSUE TITLE
NullPointerException when start leader

### ISSUE THREAD

**Issue by xfeep** [SnappyDataInc/snappydata#651]
The error message in start_snappyleader.log

```

[TRACE 2017/06/11 02:18:37.775 CST GFXD:error:FabricServiceAPI <serverConnector> tid=0xf] XJ040 error occurred while starting server : java.sql.SQLException(XJ040): Failed to start database 'gemfirexd', see the cause for details.
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.spark.SparkException: External scheduler cannot be instantiated
	at com.gemstone.gemfire.internal.cache.CacheServerLauncher$AsyncServerLauncher.getSystem(CacheServerLauncher.java:1024)
	at com.gemstone.gemfire.internal.cache.CacheServerLauncher.server(CacheServerLauncher.java:900)
	at com.pivotal.gemfirexd.tools.internal.GfxdServerLauncher.run(GfxdServerLauncher.java:807)
	at io.snappydata.tools.LeaderLauncher.run(LeaderLauncher.scala:87)
	at io.snappydata.tools.LeaderLauncher$.main(LeaderLauncher.scala:150)
	at io.snappydata.tools.LeaderLauncher.main(LeaderLauncher.scala)
Caused by: java.lang.RuntimeException: org.apache.spark.SparkException: External scheduler cannot be instantiated
Caused by: org.apache.spark.SparkException: External scheduler cannot be instantiated
	at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2537)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:515)
	at io.snappydata.impl.LeadImpl.start(LeadImpl.scala:160)
	at io.snappydata.impl.ServerImpl.start(ServerImpl.scala:32)
	at io.snappydata.tools.LeaderLauncher.startServerVM(LeaderLauncher.scala:96)
	at com.pivotal.gemfirexd.tools.internal.GfxdServerLauncher.connect(GfxdServerLauncher.java:181)
	at com.gemstone.gemfire.internal.cache.CacheServerLauncher$AsyncServerLauncher.run(CacheServerLauncher.java:1015)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException(XJ040): Failed to start database 'gemfirexd', see the cause for details.
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedSQLException.wrapStandardException(EmbedSQLException.java:158)
	at com.pivotal.gemfirexd.internal.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:726)
	at com.pivotal.gemfirexd.internal.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:656)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2994)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:708)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:94)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:75)
	at com.pivotal.gemfirexd.internal.jdbc.Driver40.getNewEmbedConnection(Driver40.java:95)
	at com.pivotal.gemfirexd.internal.jdbc.InternalDriver.connect(InternalDriver.java:351)
	at com.pivotal.gemfirexd.internal.jdbc.InternalDriver.connect(InternalDriver.java:219)
	at com.pivotal.gemfirexd.internal.jdbc.InternalDriver.connect(InternalDriver.java:195)
	at io.snappydata.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:153)
	at com.pivotal.gemfirexd.internal.engine.fabricservice.FabricServiceImpl.startImpl(FabricServiceImpl.java:279)
	at com.pivotal.gemfirexd.internal.engine.fabricservice.FabricServerImpl.start(FabricServerImpl.java:60)
	at io.snappydata.impl.LeadImpl.internalStart(LeadImpl.scala:188)
	at io.snappydata.impl.LeadImpl$.invokeLeadStart(LeadImpl.scala:489)
	at org.apache.spark.scheduler.cluster.SnappyEmbeddedModeClusterManager.initialize(SnappyEmbeddedModeClusterManager.scala:88)
	at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2532)
	... 7 more
Caused by: ERROR XJ040: Failed to start database 'gemfirexd', see the cause for details.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.postCreate(FabricDatabase.java:585)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:658)
	... 20 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at io.snappydata.impl.SnappyHiveCatalog.handleFutureResult(SnappyHiveCatalog.java:165)
	at io.snappydata.impl.SnappyHiveCatalog.getAllStoreTablesInCatalog(SnappyHiveCatalog.java:126)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.checkSnappyCatalogConsistency(FabricDatabase.java:609)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.postCreate(FabricDatabase.java:548)
	... 21 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.snappydata.impl.SnappyHiveCatalog.handleFutureResult(SnappyHiveCatalog.java:163)
	... 24 more
Caused by: java.lang.NullPointerException
	at io.snappydata.impl.SnappyHiveCatalog$HMSQuery.isTableInStoreDD(SnappyHiveCatalog.java:342)
	at io.snappydata.impl.SnappyHiveCatalog$HMSQuery.call(SnappyHiveCatalog.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Error starting server process: null
```

**Comment by sumwale** [comment]
@xfeep can you give details of the build being used and also attach the full lead logs?

**Comment by xfeep** [comment]
@sumwale 

We use snappydata-0.8-without-hadoop-bin.tar.gz.

The full log is attached. 

[snappy-lead-log.zip](https://github.com/SnappyDataInc/snappydata/files/1066563/snappy-lead-log.zip)

**Comment by hbhanawat** [comment]
@xfeep Is it an upgrade case? I can see the following table USER_MKT_SN in the lead logs which is already present. Could you please tell the steps that lead you to this error?

**Comment by xfeep** [comment]
@hbhanawat No. I use a newly installed snappydata-0.8 cluster.
Before got this error I did 
1. create a table, e.g. table_a then I got /snappydata-data-path/table_a can not created or is not a directory error.
1. mkdir /snappydata-data-path/table_a , then create table_a again and it is ok.
2. load a parquet file and insert all records into table_a
3. do some queries
4. create table_b
5. insert a large mount of records into table_b
6. drop table_b
7. stop snappydata
8. increase memory size in the configuration file
9. start snappydata and can not start it

**Comment by sumwale** [comment]
@xfeep Sorry for not getting back earlier on this. Can you try with latest 1.0 RC release (1.0 final release will be available later this week) and see?
