### ISSUE TITLE
Fail to convert org.apache.spark.unsafe.types.UTF8String

### ISSUE THREAD

**Issue by mp-calebs** [SnappyDataInc/snappydata#659]
SnappyData version: 0.9

We just downloaded snappyData 0.9 and got the following exception from our unit tests that work with SnappyData 0.8. 

Caused by: com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: shei1(93178)<v1>:56748, caused by org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 18.0 failed 4 times, most recent failure: Lost task 0.3 in stage 18.0 (TID 419, shei1): java.sql.SQLDataException(22005): An attempt was made to get a data value of type 'VARCHAR' from a data value of type 'org.apache.spark.unsafe.types.UTF8String' for column '1'.
	at com.pivotal.gemfirexd.internal.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:100)
	at com.pivotal.gemfirexd.internal.impl.jdbc.Util.newEmbedSQLException(Util.java:110)
	at com.pivotal.gemfirexd.internal.impl.jdbc.Util.newEmbedSQLException(Util.java:116)
	at com.pivotal.gemfirexd.internal.impl.jdbc.Util.generateCsSQLException(Util.java:237)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedPreparedStatement.dataTypeConversion(EmbedPreparedStatement.java:1991)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedPreparedStatement.setObject(EmbedPreparedStatement.java:1573)
	at org.apache.spark.sql.execution.columnar.ExternalStoreUtils$.setStatementParameters(ExternalStoreUtils.scala:428)
	at org.apache.spark.sql.execution.row.RowFormatScanRDD.computeResultSet(RowFormatScanRDD.scala:195)
	at org.apache.spark.sql.execution.row.RowFormatScanRDD.compute(RowFormatScanRDD.scala:263)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:320)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:284)
	at org.apache.spark.sql.execution.WholeStageCodegenRDD.compute(WholeStageCodegenExec.scala:496)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:320)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:284)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:79)
	at org.apache.spark.scheduler.Task.run(Task.scala:107)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

It looks like class EmbedPareparedStatement.setObject looks only for an instanceof String but not instanceof  org.apache.spark.unsafe.types.UTF8String.

**Comment by ymahajan** [comment]
@mp-calebs, we are looking into it. You may be right about UTF8String handling, but the code hasn't changed in 0.9 in this area. It would be good if you could share a test harness with us, may be the create table ddl and the query would be good for now.

**Comment by mp-calebs** [comment]
Table:
CREATE TABLE IF NOT EXISTS mds.ds_property (
  ds_name VARCHAR(250) NOT NULL,
  ds_column VARCHAR(150) NOT NULL,
  property VARCHAR(150) NOT NULL,
  ds_class_id CHAR(1) NOT NULL,
  string_value VARCHAR(1024),
  long_value BIGINT,
  double_value DOUBLE,
  updated_ts TIMESTAMP NOT NULL,
PRIMARY KEY (ds_name, ds_column, property))
USING ROW OPTIONS (
  PARTITION_BY 'ds_name',
  COLOCATE_WITH 'mds.dataset',
  PERSISTENT 'SYNCHRONOUS',
  DISKSTORE 'metadataset',
  REDUNDANCY '2');

Query:
SELECT p.ds_name,p.ds_column,p.property,p.ds_class_id,p.string_value,p.long_value,p.double_value FROM mds.ds_property p WHERE  (p.ds_column = '-' AND p.property = 'FAMILY' AND p.string_value = 'FindDatasetTestFamily_1') OR (p.ds_column = '-' AND p.property = 'DOUBLE_PROP' AND p.double_value <= 0.2) OR (p.ds_class_id = 'C' AND p.property = 'DOUBLE_PROP' AND p.double_value > 0.2) OR (p.ds_class_id = 'C' AND p.property = 'DOUBLE_PROP' AND p.double_value < 0.2)

**Comment by mp-calebs** [comment]
After I change EmbedPareparedStatement.java as the following, I don't see any exception any more. 

		if (x instanceof String) {
			setString(parameterIndex, (String) x);
			return;
		}

		// CHANGE_BEGIN
		// ISSUE: https://github.com/SnappyDataInc/snappydata/issues/659
		if (x instanceof org.apache.spark.unsafe.types.UTF8String) {
			setString(parameterIndex, x.toString());
			return;
		}
		// CHANGE_END

		if (x instanceof Boolean) {
			setBoolean(parameterIndex, ((Boolean) x).booleanValue());
			return;
		}

**Comment by vivekwiz** [comment]
@mp-calebs Thanks for identifying issue and proposing a fix.

UTF8String should have not reached here. This is an issue which only shows up after creating multiple indexes on same varchar column. We have identified a fix and will be checking-in that soon.

**Comment by vivekwiz** [comment]
You can check further progress on: https://jira.snappydata.io/browse/SNAP-1737. Hence closing this issue.
