### ISSUE TITLE
when RDD.collect() do serialization, this exception happens!

### ISSUE THREAD

**Issue by theseusyang** [SnappyDataInc/snappydata#671]
we encounter this problem, when RDD.collect() do serialization,  ( when using  -J-Dspark.serializer= org.apache.spark.serializer.JavaSerializer  or PooledKryoSerializer  ) :

java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.sql.execution.WholeStageCodegenRDD

stacktrace:

```log 17/06/23 16:34:24.106 CST pool-23-thread-2<tid=0x100> ERROR JobManagerActor: Exception from job df13790b-2c59-429a-ad99-9c315026c652: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 69, node76.st): java.lang.ClassCastException: cannot assign instance of scal a.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.sql.execution.WholeStageCodegenRDD at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133) at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2251) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:479) at sun.reflect.GeneratedMethodAccessor316.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75) at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:75) at org.apache.spark.scheduler.Task.run(Task.scala:107) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:277) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:748)

Driver stacktrace: at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1469) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1457) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1456) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1456) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:809) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:809) at scala.Option.foreach(Option.scala:257) at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:809) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1682) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1637) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1626) at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48) at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630) at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899) at org.apache.spark.SparkContext.runJob(SparkContext.scala:1912) at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925) at org.apache.spark.SparkContext.runJob(SparkContext.scala:1939) at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:913) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112) at org.apache.spark.rdd.RDD.withScope(RDD.scala:359) at org.apache.spark.rdd.RDD.collect(RDD.scala:912) at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:290) at org.apache.spark.sql.execution.ExecutePlan$$anonfun$sideEffectResult$1.apply(ExistingPlans.scala:191) at org.apache.spark.sql.execution.ExecutePlan$$anonfun$sideEffectResult$1.apply(ExistingPlans.scala:191) at org.apache.spark.sql.CachedDataFrame$.withNewExecutionId(CachedDataFrame.scala:325) at org.apache.spark.sql.execution.ExecutePlan.sideEffectResult$lzycompute(ExistingPlans.scala:190) at org.apache.spark.sql.execution.ExecutePlan.sideEffectResult(ExistingPlans.scala:186) at org.apache.spark.sql.execution.ExecutePlan.doExecute(ExistingPlans.scala:201) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:115) at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:136) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:133) at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:114) at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:86) at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:86) at org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:259) at org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:239) at search.SnappyJobInsertDataFromTextFile01.foo(SnappyJobInsertDataFromTextFile01.scala:77) at search.SnappyJobInsertDataFromTextFile01.runSnappyJob(SnappyJobInsertDataFromTextFile01.scala:87) at org.apache.spark.sql.SnappySQLJob$class.runJob(SnappySessionFactory.scala:75) at search.SnappyJobInsertDataFromTextFile01.runJob(SnappyJobInsertDataFromTextFile01.scala:25) at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:315) at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:748)

```

**Comment by theseusyang** [comment]
this is a custom job way:
snSession.sql("select * from " + table).mapPartitions(partition => {

            val topKHeapInPartition = new mutable.PriorityQueue[(String, Float)]()(OpqOrdering)

            partition.foreach(r => {
                ...
				// add to topKHeapInPartition
            })
			
            topKHeapInPartition.toIterator

        }).collect

**Comment by dshirish** [comment]
I am unable to reproduce this issue after trying a code similar to code you pasted. It will help if you could you share you log files (lead logs and server logs), if possible a sample program that can reproduce the issue and steps you used to run the program?

**Comment by hbhanawat** [comment]
The exception stack trace indicates exception while inserting data? 

org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:239) at search.SnappyJobInsertDataFromTextFile01.foo(SnappyJobInsertDataFromTextFile01.scala:77

**Comment by theseusyang** [comment]
17/06/28 14:42:06.965 CST Executor task launch worker-1<tid=0x9a> INFO SnappyMutableURLClassLoader: Removing jar_niko_47-2017-06-28T13_35_53.558+08_00.jar from Spark root directory
17/06/28 14:42:06.966 CST Executor task launch worker-1<tid=0x9a> INFO SnappyExecutor: As some of the Jars have been deleted, setting up a new ClassLoader for subsequent Threads
17/06/28 14:42:06.967 CST Executor task launch worker-1<tid=0x9a> INFO SnappyExecutor: removed jar jar_niko_47-2017-06-28T13_35_53.558+08_00.jar
17/06/28 14:42:06.981 CST Executor task launch worker-1<tid=0x9a> ERROR SnappyExecutor: Exception in task 0.0 in stage 1.0 (TID 4)

**Comment by theseusyang** [comment]
If first running this code, it is normal, but second it happened this exception:

ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apa
che.spark.rdd.MapPartitionsRDD

**Comment by rishitesh** [comment]
Are you using SnappyJobs to submit the code ? If yes are you changing any dependencies in between two jobs ? Is it a stream job ?

**Comment by theseusyang** [comment]
Yes, I am using SnappyJobs, But I cant change anything about build-in jar packages including Spark

**Comment by sumwale** [comment]
@theseusyang Were you able to get past this issue and is it still seen in 1.0 RC release?
