### ISSUE TITLE
NullPointerException when lead is retrieving tables from hive metastore

### ISSUE THREAD

**Issue by mp-calebs** [SnappyDataInc/snappydata#710]
SnappyData 0.9

When I have hive-site.xml configured to a hive metastore, I get the following error from the lead service. 

Caused by: ERROR XJ040: Failed to start database 'gemfirexd', see the cause for details.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.postCreate(FabricDatabase.java:587)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:659)
	... 20 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at io.snappydata.impl.SnappyHiveCatalog.handleFutureResult(SnappyHiveCatalog.java:196)
	at io.snappydata.impl.SnappyHiveCatalog.getAllStoreTablesInCatalog(SnappyHiveCatalog.java:152)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.checkSnappyCatalogConsistency(FabricDatabase.java:611)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.postCreate(FabricDatabase.java:550)
	... 21 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.snappydata.impl.SnappyHiveCatalog.handleFutureResult(SnappyHiveCatalog.java:194)
	... 24 more
Caused by: java.lang.NullPointerException
	at io.snappydata.impl.SnappyHiveCatalog$HMSQuery.isTableInStoreDD(SnappyHiveCatalog.java:450)
	at io.snappydata.impl.SnappyHiveCatalog$HMSQuery.call(SnappyHiveCatalog.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

**Comment by mp-calebs** [comment]
It seems SnappyHiveCatalog.isTableInStoreDD(String type) should check if the given type is null or not.

**Comment by dshirish** [comment]
@mp-calebs 

SnappyData internally initializes  Hive mestastore client that creates all tables required by it on SnappyData server itself. As such users are not required to configure their own hive-site.xml and if it is configured to point to a different Hive metastore URI, it  will not work as Hive mestastore's tables are expected to be on SnappyData servers. So you can remove your hive-site.xml and then start then start fresh instances SnappyData system and this exception should go away.

**Comment by sumwale** [comment]
@mp-calebs As mentioned by @dshirish using external hive catalog is not supported with SnappySession and will cause trouble like above. If there is some specific requirement for using external hive meta-store then please open a new issue with details on the requirements.
