### ISSUE TITLE
org.apache.spark.sql.TableNotFoundException when trying to create a table

### ISSUE THREAD

**Issue by TariqAbughofa** [SnappyDataInc/snappydata#801]
I am trying to create a table from spark shell (snappydata 0.9) like this:
```
snappy.createTable(tableName = "vertexTable",
     |         provider = "column", // Create a SnappyData Column table
     |         schema = vertexTableSchema,
     |         options = Map.empty[String, String], // Map for options.
     |         allowExisting = true)
```

and I am getting the follwoing error:
```
org.apache.spark.sql.TableNotFoundException: Table 'APP.VERTEXTABLE' not found;
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog$$anonfun$3.apply(SnappyStoreHiveCatalog.scala:449)
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog$$anonfun$3.apply(SnappyStoreHiveCatalog.scala:449)
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
  at scala.collection.AbstractMap.getOrElse(Map.scala:59)
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog.lookupRelation(SnappyStoreHiveCatalog.scala:448)
  at org.apache.spark.sql.SmartConnectorHelper.createTable(SmartConnectorHelper.scala:112)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:969)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:786)
```
this is the spark-shell command:

> spark-shell  --master yarn --conf spark.snappydata.connection=locator.local:1527 --packages "SnappyDataInc:snappydata:0.9-s_2.11"

**Comment by ymahajan** [comment]
@TariqAbughofa  It may be be possible that the table really exists in SnappyData cluster. 
You can verify through SnappyData dashboard.

Which spark version are you using, also does this work with local mode (rather than yarn)?

As a workaround, you could also try creating table using SQL like 

snappy.sql("create table simple(a int) using column options()")

**Comment by TariqAbughofa** [comment]
thanks for your reply!
the error states that the table "does not" exist though which is why it's .
I tried the command you suggested which gave me a more confusing error:
`java.sql.SQLException: (SQLState=38000 Severity=20000) (Server=*******[1527] Thread=pool-3-thread-14) The exception 'com.gemstone.gemfire.cache.execute.FunctionException: ERROR 38000: The exception 'createTable: Table APP.SIMPLE already exists.;' was thrown while evaluating an expression.' was thrown while evaluating an expression.`

**Comment by ymahajan** [comment]
I had tried your steps, but was getting a different error. 

snappydata-0.9-bin]$ ./bin/spark-shell --master yarn --conf spark.snappydata.connection=localhost:1527 --packages "SnappyDataInc:snappydata:0.9-s_2.11"
scala> val snappy = new org.apache.spark.sql.SnappySession(sc)
scala> import org.apache.spark.sql.types.{StringType, StructField, StructType}
scala> val vertexTableSchema = StructType(Array(StructField("msg", StringType, true)))
scala> snappy.createTable(tableName = "vertexTable",
     |      |         provider = "column", // Create a SnappyData Column table
     |      |         schema = vertexTableSchema,
     |      |         options = Map.empty[String, String], // Map for options.
     |      |         allowExisting = true)
17/08/21 11:46:37 ERROR metastore.RetryingHMSHandler: AlreadyExistsException(message:Database DEFAULT already exists)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.create_database(HiveMetaStore.java:891)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


But the sql case worked for me - 

scala> snappy.sql("create table simple(a int) using column options()")
res1: org.apache.spark.sql.CachedDataFrame = []

scala> snappy.sql("select * from simple").show
+---+                                                                           
|  A|
+---+
+---+

**Comment by ymahajan** [comment]
And in spite of the error, vertexTable was created in SnappyData. The table was shown in dashboard and even through query. 

scala> snappy.sql("select * from vertexTable").show
+---+                                                                           
|MSG|
+---+
+---+

**Comment by TariqAbughofa** [comment]
do you know why it's using database DEFAULT for you while it's APP for me? Is their a way to change the database?

**Comment by ymahajan** [comment]
Please try this, it worked for me - 

scala> snappy.sql("set schema newapp")
res3: org.apache.spark.sql.CachedDataFrame = []

scala> snappy.createTable(tableName = "vertexTable",
     |      |         provider = "column", // Create a SnappyData Column table
     |      |         schema = vertexTableSchema,
     |      |         options = Map.empty[String, String], // Map for options.
     |      |         allowExisting = true)
res4: org.apache.spark.sql.DataFrame = [MSG: string]

**Comment by TariqAbughofa** [comment]
it worked to change the schema but still getting the same error:

```
org.apache.spark.sql.TableNotFoundException: Table 'NEWAPP.VERTEXTABLE' not found;
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog$$anonfun$3.apply(SnappyStoreHiveCatalog.scala:449)
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog$$anonfun$3.apply(SnappyStoreHiveCatalog.scala:449)
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
  at scala.collection.AbstractMap.getOrElse(Map.scala:59)
  at org.apache.spark.sql.hive.SnappyStoreHiveCatalog.lookupRelation(SnappyStoreHiveCatalog.scala:448)
  at org.apache.spark.sql.SmartConnectorHelper.createTable(SmartConnectorHelper.scala:112)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:969)
  at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:786)
```

**Comment by ymahajan** [comment]
@TariqAbughofa Can you please try with this option in your spark-shell launch command

--conf spark.sql.catalogImplementation=in-memory

**Comment by TariqAbughofa** [comment]
I tried adding the option. still nothing changed

**Comment by ymahajan** [comment]
@TariqAbughofa This should work with the 1.0.0 RC build. Please try with this release - 
https://github.com/SnappyDataInc/snappydata/releases/tag/v1.0.0-rc1
