### ISSUE TITLE
Data Import SYSCS_UTIL.IMPORT_TABLE stored procedure fails with NullPointerException

### ISSUE THREAD

**Issue by jestan** [SnappyDataInc/snappydata#819]
Data export stored procedure SYSCS_UTIL.EXPORT_TABLE works but SYSCS_UTIL.IMPORT_TABLE stored procedure fails with NullPointerException

Here is a reproducer

``` java

public class DataExportImportIssueReproducer {

    private static final String DROP_TABLE_IF_EXIST = "DROP TABLE IF EXISTS APP.SAMPLE_TABLE1;";

    private static final String CREATE_TABLE = "" +
            "CREATE TABLE APP.SAMPLE_TABLE1 (\n" +
            "  a BIGINT NOT NULL PRIMARY KEY,\n" +
            "  b TIMESTAMP,\n" +
            "  c VARCHAR(36) NOT NULL,\n" +
            "  d VARCHAR(48) NOT NULL,\n" +
            "  e DECIMAL(15,3) NOT NULL,\n" +
            "  f DECIMAL(15,3) NOT NULL,\n" +
            "  g VARCHAR(3) NOT NULL,\n" +
            "  h VARCHAR(12) NOT NULL,\n" +
            "  i VARCHAR(32) NOT NULL,\n" +
            "  j VARCHAR(16) NOT NULL,\n" +
            "  k VARCHAR(32) NOT NULL,\n" +
            "  l DECIMAL(15,3) NOT NULL,\n" +
            "  m VARCHAR(32) NOT NULL,\n" +
            "  n DECIMAL(15,3) NOT NULL,\n" +
            "  o VARCHAR(32) NOT NULL,\n" +
            "  p DECIMAL(15,3) NOT NULL,\n" +
            "  q VARCHAR(32) NOT NULL,\n" +
            "  r DECIMAL(15,3) NOT NULL,\n" +
            "  s VARCHAR(32) NOT NULL,\n" +
            "  t VARCHAR(16) NOT NULL,\n" +
            "  u VARCHAR(32) NOT NULL,\n" +
            "  v VARCHAR(64) NOT NULL,\n" +
            "  w VARCHAR(16) NOT NULL,\n" +
            "  x VARCHAR(16),\n" +
            "  y VARCHAR(32),\n" +
            "  z VARCHAR(128)\n" +
            ") USING ROW OPTIONS (PARTITION_BY 'a', PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT');";



    private static final String INSERT_ROWS = "" +
            "INSERT INTO APP.SAMPLE_TABLE1 VALUES " +
            " (1, CURRENT_TIMESTAMP, '', '', 10.00, 0.00, '', '', '', '', '', 0.00, '', 0.00, '', 0.00, '', 0.00, '', '', '', '', '', '', '', '');" ;


    private static final String TRUNCATE_TABLE = "TRUNCATE TABLE APP.SAMPLE_TABLE1;";

    private static final String EXPORT_TABLE = "CALL SYSCS_UTIL.EXPORT_TABLE ('APP', 'SAMPLE_TABLE1', '/tmp/%s.del', null, null, null);";

    private static final String IMPORT_TABLE = "CALL SYSCS_UTIL.IMPORT_TABLE ('APP', 'SAMPLE_TABLE1', '/tmp/%s.del', null, null, null, 0);";



    public static void main(String[] args) throws Exception {

        try (Connection connection = DriverManager.getConnection("jdbc:snappydata://localhost:1527")) {

            try (Statement statement = connection.createStatement()) {


                executeSQL(statement, DROP_TABLE_IF_EXIST);
                executeSQL(statement, CREATE_TABLE);

                executeSQL(statement, INSERT_ROWS);

                long randomFileName = System.currentTimeMillis();

                executeSPC(connection, String.format(EXPORT_TABLE, randomFileName));

                executeSQL(statement, TRUNCATE_TABLE);

                executeSQL(statement, String.format(IMPORT_TABLE, randomFileName));


            }

        }


    }


    private static void executeSQL(Statement statement, String sql) throws Exception {
        System.out.println("...................");
        System.out.println("...................");

        System.out.println("EXECUTING " + sql);

        statement.execute(sql);

        System.out.println("...................");
        System.out.println("...................");
    }

    private static void executeSPC(Connection connection, String spc) throws Exception {
        System.out.println("...................");
        System.out.println("...................");

        System.out.println("EXECUTING " + spc);

        CallableStatement statement = connection.prepareCall(spc);

        statement.execute();

        System.out.println("...................");
        System.out.println("...................");
    }



}

```

And Output is

```
Aug 31, 2017 3:19:21 PM java.util.logging.LogManager$RootLogger log
INFO: Starting client on '172.16.1.21' with ID='400|2017/08/31 15:19:21.201 IST' Source-Revision=5d896818f67dd9c6ba1de2bc027384c4991cd1a8
...................
...................
EXECUTING DROP TABLE IF EXISTS APP.SAMPLE_TABLE1;
...................
...................
...................
...................
EXECUTING CREATE TABLE APP.SAMPLE_TABLE1 (
  a BIGINT NOT NULL PRIMARY KEY,
  b TIMESTAMP,
  c VARCHAR(36) NOT NULL,
  d VARCHAR(48) NOT NULL,
  e DECIMAL(15,3) NOT NULL,
  f DECIMAL(15,3) NOT NULL,
  g VARCHAR(3) NOT NULL,
  h VARCHAR(12) NOT NULL,
  i VARCHAR(32) NOT NULL,
  j VARCHAR(16) NOT NULL,
  k VARCHAR(32) NOT NULL,
  l DECIMAL(15,3) NOT NULL,
  m VARCHAR(32) NOT NULL,
  n DECIMAL(15,3) NOT NULL,
  o VARCHAR(32) NOT NULL,
  p DECIMAL(15,3) NOT NULL,
  q VARCHAR(32) NOT NULL,
  r DECIMAL(15,3) NOT NULL,
  s VARCHAR(32) NOT NULL,
  t VARCHAR(16) NOT NULL,
  u VARCHAR(32) NOT NULL,
  v VARCHAR(64) NOT NULL,
  w VARCHAR(16) NOT NULL,
  x VARCHAR(16),
  y VARCHAR(32),
  z VARCHAR(128)
) USING ROW OPTIONS (PARTITION_BY 'a', PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT');
...................
...................
...................
...................
EXECUTING INSERT INTO APP.SAMPLE_TABLE1 VALUES  (1, CURRENT_TIMESTAMP, '', '', 10.00, 0.00, '', '', '', '', '', 0.00, '', 0.00, '', 0.00, '', 0.00, '', '', '', '', '', '', '', '');
...................
...................
...................
...................
EXECUTING CALL SYSCS_UTIL.EXPORT_TABLE ('APP', 'SAMPLE_TABLE1', '/tmp/1504172962328.del', null, null, null);
...................
...................
...................
...................
EXECUTING TRUNCATE TABLE APP.SAMPLE_TABLE1;
...................
...................
...................
...................
EXECUTING CALL SYSCS_UTIL.IMPORT_TABLE ('APP', 'SAMPLE_TABLE1', '/tmp/1504172962328.del', null, null, null, 0);
Exception in thread "main" java.sql.SQLException: (SQLState=38000 Severity=20000) (Server=snappydata-n2.service.solar/127.0.0.1[1556] Thread=pool-3-thread-10) The exception 'java.lang.NullPointerException' was thrown while evaluating an expression.
	at io.snappydata.thrift.SnappyDataService$execute_result$execute_resultStandardScheme.read(SnappyDataService.java:7033)
	at io.snappydata.thrift.SnappyDataService$execute_result$execute_resultStandardScheme.read(SnappyDataService.java:7010)
	at io.snappydata.thrift.SnappyDataService$execute_result.read(SnappyDataService.java:6949)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at io.snappydata.thrift.SnappyDataService$Client.recv_execute(SnappyDataService.java:256)
	at io.snappydata.thrift.SnappyDataService$Client.execute(SnappyDataService.java:239)
	at io.snappydata.thrift.internal.ClientService.execute(ClientService.java:895)
	at io.snappydata.thrift.internal.ClientStatement.execute(ClientStatement.java:720)
	at io.snappydata.thrift.internal.ClientStatement.execute(ClientStatement.java:371)
	at io.snappydata.DataExportImportIssueReproducer.executeSQL(DataExportImportIssueReproducer.java:97)
	at io.snappydata.DataExportImportIssueReproducer.main(DataExportImportIssueReproducer.java:80)
Caused by: java.rmi.ServerException: Server STACK: java.sql.SQLException(38000): The exception 'java.lang.NullPointerException' was thrown while evaluating an expression.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.unexpectedUserException(StandardException.java:776)
	at com.pivotal.gemfirexd.internal.impl.services.reflect.ReflectMethod.invoke(ReflectMethod.java:98)
	at com.pivotal.gemfirexd.internal.impl.sql.execute.CallStatementResultSet.open(CallStatementResultSet.java:132)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:593)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2159)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1283)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1005)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:971)
	at io.snappydata.thrift.server.SnappyDataServiceImpl.execute(SnappyDataServiceImpl.java:1671)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1511)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1495)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at io.snappydata.thrift.server.SnappyDataServiceImpl$Processor.process(SnappyDataServiceImpl.java:199)
	at io.snappydata.thrift.server.SnappyThriftServerThreadPool$WorkerProcess.run(SnappyThriftServerThreadPool.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.pivotal.gemfirexd.internal.impl.load.ImportBase.performImport(ImportBase.java:876)
	at com.pivotal.gemfirexd.internal.impl.load.ImportBase.performImport(ImportBase.java:366)
	at com.pivotal.gemfirexd.internal.impl.load.ImportBase.importTable(ImportBase.java:219)
	at com.pivotal.gemfirexd.internal.catalog.SystemProcedures.IMPORT_TABLE(SystemProcedures.java:1417)
	at com.pivotal.gemfirexd.internal.exe.ac825444e2x015ex3786xd4a8x0000399779302.g0(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.pivotal.gemfirexd.internal.impl.services.reflect.ReflectMethod.invoke(ReflectMethod.java:68)
	... 15 more

	at io.snappydata.thrift.common.ThriftExceptionUtil.newSQLException(ThriftExceptionUtil.java:109)
	at io.snappydata.thrift.internal.ClientStatement.execute(ClientStatement.java:736)
	... 3 more

```

**Comment by sumwale** [comment]
@jestan Are you using rowstore mode? If not then the IMPORT/EXPORT procedures are not supported in SnappyData. Use CSV provider to create an external table then insert into row table selecting from it (there is an example of using SQL to do it in a howto https://snappydatainc.github.io/snappydata/howto/#howto-sde -- for CSV create a table with "USING csv").

**Comment by jestan** [comment]
@sumwale 
The table was created using 'USING ROW OPTIONS', so I assume it is row store mode?
EXPORT_TABLE works and i got this output, but IMPORT_TABLE fails with NPE

cat /tmp/1504172796155.del

1,"2017-08-31 15:16:36.154","","",10.000,0.000,"","","","","",0.000,"",0.000,"",0.000,"",0.000,"","","","","","","",""

**Comment by sumwale** [comment]
@jestan This is a normal row table so you are not using rowstore mode (which is the old GemFireXD compatible mode and syntax). Neither of IMPORT/EXPORT procedures are supported and should be done using external tables:

```sql
CREATE EXTERNAL TABLE ... USING csv OPTIONS (path '...', header '<true/false>', inferSchema 'true');

insert into SAMPLE_TABLE1 select * from ...
```

**Comment by jestan** [comment]
@sumwale 
Thank you for the clarification, i will try with external table approach.

I think the issue is when we wants to use snappydata with JDBC/SQL, there is not much documentation available in snappydata and all references are pointing to RowStore, most of the features in RowStore documentation is working with normal row table (this is where the confusion starts), we assumed that RowStore is ROW table, didn't know about GemfireXD compatibility mode

I hope, snappydata SQL/JDBC documentation will improve in future  about supported/not supported features

**Comment by sumwale** [comment]
@jestan Thanks for your inputs. We are working to improve the docs for 1.0 @shyjaprabhu @kneeraj

**Comment by jestan** [comment]
@sumwale 
I tried with external table approach.

This is what i have in the file.

cat /tmp/1504172796155.del

```csv

1,"2017-08-31 15:16:36.154","","",10.000,0.000,"","","","","",0.000,"",0.000,"",0.000,"",0.000,"","","","","","","",""

```


```sql
CREATE EXTERNAL TABLE SAMPLE_TABLE1_STAGING  USING csv OPTIONS (path '/tmp/1504172796155.del', header 'false', inferSchema 'true');
```

```sql
INSERT into SAMPLE_TABLE1 select * from SAMPLE_TABLE1_STAGING;
```
ERROR 23502: (SQLState=23502 Severity=20000) (Server=localhost/127.0.0.1[1555] Thread=pool-3-thread-1) Column 'C'  cannot accept a NULL value.

It seems I can load the data into external table, but insert into steps fails because CREATE EXTERNAL TABLE with CSV takes "" columns as null.

I have a row table with following definition and it didn't work.

```sql
CREATE TABLE APP.SAMPLE_TABLE1 (
  a BIGINT NOT NULL PRIMARY KEY,
  b TIMESTAMP,
  c VARCHAR(36) NOT NULL,
  d VARCHAR(48) NOT NULL,
  e DECIMAL(15,3) NOT NULL,
  f DECIMAL(15,3) NOT NULL,
  g VARCHAR(3) NOT NULL,
  h VARCHAR(12) NOT NULL,
  i VARCHAR(32) NOT NULL,
  j VARCHAR(16) NOT NULL,
  k VARCHAR(32) NOT NULL,
  l DECIMAL(15,3) NOT NULL,
  m VARCHAR(32) NOT NULL,
  n DECIMAL(15,3) NOT NULL,
  o VARCHAR(32) NOT NULL,
  p DECIMAL(15,3) NOT NULL,
  q VARCHAR(32) NOT NULL,
  r DECIMAL(15,3) NOT NULL,
  s VARCHAR(32) NOT NULL,
  t VARCHAR(16) NOT NULL,
  u VARCHAR(32) NOT NULL,
  v VARCHAR(64) NOT NULL,
  w VARCHAR(16) NOT NULL,
  x VARCHAR(16),
  y VARCHAR(32),
  z VARCHAR(128)
) USING ROW OPTIONS (PARTITION_BY 'a', PERSISTENCE 'ASYNC', OVERFLOW 'true', EVICTION_BY 'LRUHEAPPERCENT');
```

Is it the expected behavior of CREATE EXTERNAL TABLE with CSV OPTION?

When I remove the NOT NULL constraints it works.

**Comment by jestan** [comment]
@sumwale 

I think spark-shell will be a better option to load/store the data.
I just had a look at https://github.com/SnappyDataInc/snappydata/issues/745

I will give a try with spark-shell.

**Comment by sumwale** [comment]
@jestan you can use a different null value string using nullValue option.

```sql
CREATE EXTERNAL TABLE SAMPLE_TABLE1_STAGING  USING csv OPTIONS (path '/tmp/1504172796155.del', header 'false', inferSchema 'true', nullValue 'NULL');
```

See full set of options in spark-csv docs: https://github.com/databricks/spark-csv (this is integrated in Spark since 2.0.0). The behavior of spark-shell will be identical, but it might be easier to use.

**Comment by jestan** [comment]
@sumwale 
Thank you, using snappy-shell with direct sql is easier than writing Scala in spark-shell.
Similarly, is there any easy way to export data to csv from snappy-data (except spark-csv/dataframewriter) ?

**Comment by sumwale** [comment]
@jestan Similar way:
```sql
CREATE EXTERNAL TABLE SAMPLE_TABLE1_OUTPUT USING csv OPTIONS (path '...', ...) AS (select * from SAMPLE_TABLE1)
```

See the set of write options available in the docs https://github.com/databricks/spark-csv

**Comment by jestan** [comment]
@sumwale 
Thanks
