### ISSUE TITLE
snappydata-1.0.0-bin not able to create external tables on files in HDFS

### ISSUE THREAD

**Issue by asishbose** [SnappyDataInc/snappydata#875]
Hi

I am facing authentication problems with snappydata over a kerberized hadoop system. 
The user for snappy on every of the nodes in snappy cluster has a valid ticket and hadoop reads can be seemlessly done from them. 
I guess it should be about a configuration that I am missing somehow. Can someone help me here?

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.io.IOException: Failed on local exception: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]; Host Details : local host is: "hslave13.nokia.com/50.50.50.134"; destination host is: "hmaster2.nokia.com":8020;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

============================================================
klist::
Valid starting     Expires            Service principal
10/11/17 11:45:01  10/12/17 11:45:01  krbtgt/NOKIA.COM@NOKIA.COM
        renew until 10/18/17 11:45:01
hadoop fs -ls / ::::
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Found 8 items
drwxr-xr-x   - hadoop supergroup          0 2017-10-07 23:48 /analytics
drwx------   - hadoop supergroup          0 2017-10-10 13:24 /hbase
drwxr-xr-x   - hadoop supergroup          0 2017-10-07 22:15 /mnt
drwxr-xr-x   - hadoop supergroup          0 2017-10-07 23:30 /ngdb
drwxrwxrwx   - hadoop supergroup          0 2017-10-11 12:20 /snappy
drwxrwx---   - hadoop supergroup          0 2017-10-07 22:02 /tmp
drwxr-xr-x   - hadoop supergroup          0 2017-10-11 03:04 /user
drwx-wx-wx   - hadoop supergroup          0 2017-10-07 01:04 /var
Ticket cache: FILE:/tmp/krb5cc_999
Default principal: snappy/hslave13.nokia.com@NOKIA.COM

----------------------------------------------------------------------------------------------------
[snappy@hmaster1 snappydata-1.0.0-bin]$ snappy
SnappyData version 1.0.0
snappy>  connect client 'hslave1:1527;query-HDFS=true';
Oct 11, 2017 1:21:36 PM java.util.logging.LogManager$RootLogger log
INFO: Starting client on 'hmaster1.nokia.com' with ID='127645|2017/10/11 13:21:36.905 IST' Source-Revision=e6cfbfdb0f14ee87261381934075b7f37672a99d
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/nsn/ngdb/snappydata-1.0.0-bin/jars/snappydata-zeppelin-0.7.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/nsn/ngdb/snappydata-1.0.0-bin/jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Using CONNECTION0
snappy> **CREATE EXTERNAL TABLE sd_device_2 USING PARQUET OPTIONS (path 'hdfs://hmaster2.nokia.com:8020/snappy/dp_device_1', header 'true', inferSchema 'true');**
ERROR 38000: (SQLState=38000 Severity=20000) (Server=hslave17/50.50.50.138[1527] Thread=pool-1-thread-1) The exception 'com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: hslave17(126985)<v16>:13461, caused by org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 21.0 failed 4 times, most recent failure: Lost task 0.3 in stage 21.0 (TID 166, hslave13.nokia.com, executor hslave13(114622)<v12>:33004): java.io.IOException: Failed on local exception: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]; Host Details : local host is: "hslave13.nokia.com/50.50.50.134"; destination host is: "hmaster2.nokia.com":8020;
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
        at org.apache.hadoop.ipc.Client.call(Client.java:1479)
        at org.apache.hadoop.ipc.Client.call(Client.java:1412)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
        at com.sun.proxy.$Proxy20.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy21.getBlockLocations(Unknown Source)
        at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1226)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1213)
        at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1201)
        at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306)
        at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272)
        at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:264)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1526)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:407)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$readParquetFootersInParallel$1.apply(ParquetFileFormat.scala:506)
        at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$readParquetFootersInParallel$1.apply(ParquetFileFormat.scala:500)
        at scala.collection.parallel.AugmentedIterableIterator$class.flatmap2combiner(RemainsIterator.scala:132)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.flatmap2combiner(ParVector.scala:62)
        at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1072)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1068)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
        at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:378)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:443)
        at scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Tasks.scala:426)
        at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
        at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:958)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:953)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:687)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:650)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:737)
        at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
        at org.apache.hadoop.ipc.Client.call(Client.java:1451)
        ... 57 more
Caused by: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
        at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:172)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:396)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
        at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:729)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:725)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
        ... 60 more

Driver stacktrace:' was thrown while evaluating an expression.
snappy>

**Comment by ashetkar** [comment]
To isolate the issue, can you check if the same 'CREATE EXTERNAL TABLE ...' command works from a spark shell?

`./bin/spark-shell --conf spark.snappydata.connection=<locatorhost:1527> `
`scala> spark.sql("CREATE EXTERNAL TABLE ...")`

And if it works fine, you can check executing it on a SnappySession:

`scala> val sns = new org.apache.spark.sql.SnappySession(sc)`
`scala> import org.apache.spark.sql._`
`scala> sns.sql("CREATE EXTERNAL TABLE DIFFERENT_NAME ...")`

**Comment by asishbose** [comment]
Are you looking at spark included in snappy package or separate spark ?

**Comment by asishbose** [comment]
The External table command works fine without kereberos. So to use with kerberos whats the configuration other than the principals , keyab and valid ticket.  I have also added the new users details in hadoops core-site.xml

**Comment by asishbose** [comment]
Same errror from spark provided from snappy too ::::

**scala> spark.sql("create temporary table dp_device_1 (dt string,TECHNOLOGY string,REGION string,  device_capability string COMMENT 'DEVICE_CAPABILITY.', device_type string COMMENT 'device_type', marketing_vendor string COMMENT 'MARKETING_VENDOR', handset_full_name string COMMENT 'HANDSET_FULL_NAME', apn string COMMENT 'Name of the Apn', city_id bigint COMMENT 'CITY_ID', loc_id bigint COMMENT 'Location ID', subs_type string COMMENT 'SUBS_TYPE', customer_segmentation string COMMENT 'SGSN_CUSTOMER_SEGMENT', group_id bigint COMMENT 'GROUP_ID.', parent_group_id bigint COMMENT 'PARENT_GROUP_ID.', association_id bigint COMMENT 'ASSOCIATION_ID.', subscription_plan string COMMENT 'SUBSCRIPTION_PLAN', roamer_flag string COMMENT 'ROAMER FLAG', hvc_flag bigint COMMENT 'HVC_FLAG', os_vendor string COMMENT 'OS_VENDOR from ES_TIP_DENORM_1', os_version string COMMENT 'OS_VERSION from ES_TIP_DENORM_1', attach_events bigint COMMENT 'ATTACH_EVENTS', attach_failure_events bigint COMMENT 'ATTACH_FAILURE_EVENTS', act_pdp_def_bearer_events bigint COMMENT 'ACT_PDP_DEF_BEARER_EVENTS', act_pdp_def_bearer_fail_evnts bigint COMMENT 'ACT_PDP_DEF_BEARER_FAIL_EVNTS', dedicated_bearer_fail_events bigint COMMENT 'DEDICATED_BEARER_FAIL_EVENTS', dedicated_events bigint COMMENT 'DEDICATED_EVENTS', update_events bigint COMMENT 'UPDATE_EVENTS', deactivate_events bigint COMMENT 'DEACTIVATE_EVENTS', rau_tau_events bigint COMMENT 'RAU_TAU_EVENTS', uplink_volume bigint COMMENT 'UPLINK_VOLUME', downlink_volume bigint COMMENT 'DOWNLINK_VOLUME', distinct_subscribers array<bigint> COMMENT 'DISTINCT_SUBSCRIBERS', distinct_subscriber_accessibility array<bigint> COMMENT 'DISTINCT_SUBSCRIBER_ACCESSIBILITY', distinct_subscriber_accessibility_failure array<bigint> COMMENT 'DISTINCT_SUBSCRIBER_ACCESSIBILITY_FAILURE', distinct_devices array<string> COMMENT 'DISTINCT_DEVICES', distinct_subscribers_volume array<bigint> COMMENT 'DISTINCT_SUBSCRIBERS_VOLUME', distinct_devices_accessibility_failure array<string> COMMENT 'DISTINCT_DEVICES_ACCESSIBILITY_FAILURE')  using PARQUET options(path 'hdfs://hmaster1:8020/ngdb/ps/DATA_CP_DP_1/dp_device_1',header 'true',inferSchema 'true')");**
17/10/11 16:16:43 WARN SparkSqlAstBuilder: CREATE TEMPORARY TABLE ... USING ... is deprecated, please use CREATE TEMPORARY VIEW ... USING ... instead
17/10/11 16:16:43 WARN DataSource: Error while looking for metadata directory.
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
  at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73)
  at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2110)
  at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
  at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
  at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
  at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
  at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:381)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:370)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.immutable.List.flatMap(List.scala:344)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
  at org.apache.spark.sql.execution.datasources.CreateTempViewUsing.run(ddl.scala:76)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:185)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
  ... 48 elided
Caused by: org.apache.hadoop.ipc.RemoteException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
  at org.apache.hadoop.ipc.Client.call(Client.java:1475)
  at org.apache.hadoop.ipc.Client.call(Client.java:1412)
  at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
  at com.sun.proxy.$Proxy27.getFileInfo(Unknown Source)
  at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
  at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
  at com.sun.proxy.$Proxy28.getFileInfo(Unknown Source)
  at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2108)
  ... 76 more

scala>

**Comment by ashetkar** [comment]
Have you followed the hadoop configuration as per this [Spark documentation](https://spark.apache.org/docs/2.1.1/configuration.html#inheriting-hadoop-cluster-configuration)?

If you've already done that, you could probably check the value for the property 'hadoop.rpc.protection'. Googling some forums suggested that it should be set to 'privacy' to resolve similar issue.

On another hand:
> snappy> connect client 'hslave1:1527;query-HDFS=true';

Specifying the property `query-HDFS=true` is not really needed here and is actually not relevant to SnappyData (Probably you found it on documentation related to GemFireXD).

**Comment by asishbose** [comment]
Hi,
Cloudera, has spark running with a differnt user "spark" and they have not set rpc.protection to private . They have set it to " authentication ". 
Even I have it as authentication. I am trying to add dist-classpath on spark env inside snappy. Lets see how it goes ..!

Regarding 
snappy> connect client 'hslave1:1527;query-HDFS=true';
It was just a try with no luck.

**Comment by asishbose** [comment]
Should the user for snappydata process [ Consider :: snappy ] be the admin user inside external hadoop for the processing of external tables inside external hadoop  [ Currently admin user is::  hadoop ]

**Comment by asishbose** [comment]
I used the same hive-site.xml to access the tables via spark [ here the hive-site.xml had its principals and keytabs mentioned .

Is there a way I can mention the client-site.xml when I create an external table from a file using snappy 1.0

**Comment by sumwale** [comment]
@asishbose Please refer to the Spark documentation mentioned above for HDFS configuration. GemFire's HDFSSTORE, EVICTION BY CRITERIA and related APIs are not supported in SnappyData. The Spark's way is both more efficient and more flexible.

**Comment by sumwale** [comment]
@asishbose 

> Should the user for snappydata process [ Consider :: snappy ] be the admin user inside external hadoop for the processing of external tables inside external hadoop [ Currently admin user is:: hadoop ]

Do you want to control multiple users accessing external hadoop tables as per hadoop filesystem permissions? If not, then you could either change the permissions on the directory (hdfs dfs -chmod) or disable dfs.permissions in conf/hdfs-site.xml

For multi-user access you will need to start the hadoop service appropriately. Will need to check -- I think hadoop's UserGroupInformation should work.

**Comment by raviparam** [comment]
Hi,
 Can you answer to this question?

Is there a way I can mention the client-site.xml [ as mentioned in gemfire for hdfsstore] when I create an external table from a file using snappydata 1.0.

**Comment by raviparam** [comment]
I meant while creating external table can we specify it has to use kerberos authentication, principals and keytab to connect to a secure cluster?

**Comment by sumwale** [comment]
@raviparam As mentioned in #877 the gemfire HDFSSTORE is not supported in SnappyData (see details in the comments in that issue). The configuration has to be done using conf/hdfs-site.xml and core-site.xml as mentioned in [Spark documentation](https://spark.apache.org/docs/2.1.1/configuration.html#inheriting-hadoop-cluster-configuration).

**Comment by asishbose** [comment]
@sumwale , 
Lemme explain ::

Without kerberised external hadoop, I am able to reference a file in hadoop as an external table from snappy. It works charm.

After kerberization:: It throws token errors.

Note:: now snappy runs from the same user and same node where Hadoop is installed. [ this user is also the admin user in hadoop ]
I am not sure whether in case of kerberized hadoop, is there something more I need to do in snappy when I create the external tables for snappy in hadoop. 

I require this feature to make joins with some dimension data which already exists in hadoop.
