### ISSUE TITLE
Errors happened , when create a stream table using kafka_stream options

### ISSUE THREAD

**Issue by theseusyang** [SnappyDataInc/snappydata#881]
when I create a stream table using  kafka_stream options, JavaSnappyStreamingContext throws a ArrayIndexOutOfBoundsException :

```
SparkConf conf = new SparkConf().set("spark.port.maxRetries", "100").set("spark.ui.port", "4040").setMaster("local[*]").setAppName("SparkStream1");

JavaSparkContext sc = new JavaSparkContext(conf);

Duration seconds = new Duration(1);

Dataset<Row> dataset = jsnsc.sql("create stream table streamTable( jobId string) using kafka_stream options (storagelevel 'MEMORY_AND_DISK_SER_2', rowConverter 'org.apache.spark.sql.streaming.TweetToRowsConverter', zkQuorum '127.0.0.1:2181', topics 'check_info_collect');");
```

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.spark.sql.streaming.KafkaStreamRelation$$anonfun$3.apply(KafkaStreamSource.scala:56) 
	at org.apache.spark.sql.streaming.KafkaStreamRelation$$anonfun$3.apply(KafkaStreamSource.scala:54)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.sql.streaming.KafkaStreamRelation.<init>(KafkaStreamSource.scala:54)
	at org.apache.spark.sql.streaming.KafkaStreamSource.createRelation(KafkaStreamSource.scala:37)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:328)
	at org.apache.spark.sql.SnappySession.createTable(SnappySession.scala:1028)
	at org.apache.spark.sql.CreateMetastoreTableUsing.run(SnappyDDLParser.scala:651)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.CodegenSparkFallback$$anonfun$doExecute$1.apply(CodegenSparkFallback.scala:97)
	at org.apache.spark.sql.execution.CodegenSparkFallback$$anonfun$doExecute$1.apply(CodegenSparkFallback.scala:97)
	at org.apache.spark.sql.execution.CodegenSparkFallback.executeWithFallback(CodegenSparkFallback.scala:41)
	at org.apache.spark.sql.execution.CodegenSparkFallback.doExecute(CodegenSparkFallback.scala:97)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:185)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
	at org.apache.spark.sql.SnappySession.org$apache$spark$sql$SnappySession$$super$sql(SnappySession.scala:185)
	at org.apache.spark.sql.SnappySession$$anonfun$sqlUncached$1.apply(SnappySession.scala:185)
	at org.apache.spark.sql.SnappySession$$anonfun$sqlUncached$1.apply(SnappySession.scala:185)
	at org.apache.spark.sql.execution.SnappyContextAQPFunctions.sql(SnappyContextAQPFunctions.scala:463)
	at org.apache.spark.sql.SnappySession.sqlUncached(SnappySession.scala:185)
	at org.apache.spark.streaming.SnappyStreamingContext.sql(SnappyStreamingContext.scala:151)
	at org.apache.spark.streaming.api.java.JavaSnappyStreamingContext.sql(JavaSnappyStreamingContext.scala:110)

And I find that "rowConverter 'org.apache.spark.sql.streaming.TweetToRowsConverter'" throws this exception, what is the corrent setting about this option?

**Comment by theseusyang** [comment]
@ymahajan

**Comment by ymahajan** [comment]
@theseusyang there is no Kafka param like 'zkQuorum'. 
Here are the syntax for both kafka and direct kafka, that you can refer.

    ssnc.sql("create stream table if not exists kafkaStream (" +
        " publisher string, advertiser string) " +
        " using kafka_stream options(" +
        " rowConverter 'org.apache.spark.sql.streaming.RowsConverter'," +
        s" kafkaParams 'zookeeper.connect->$zkadd;auto.offset.reset->smallest;group.id->myId'," +
        s" topics '$topic:1,$topic2:1')")


    ssnc.sql("create stream table if not exists directKafkaStream (" +
        " publisher string, advertiser string)" +
        " using directkafka_stream options(" +
        " rowConverter 'org.apache.spark.sql.streaming.RowsConverter' ," +
        s" kafkaParams 'metadata.broker.list->$brokeraddrs;auto.offset.reset->smallest'," +
        s" topics '$topic1')")

**Comment by theseusyang** [comment]
OK I try it

**Comment by x43125** [comment]
Excuse me, how to write rowconverter, or whether there are related cases
