### ISSUE TITLE
 Failed to start database 'gemfirexd', see the cause for details.

### ISSUE THREAD

**Issue by yashwanth2804** [SnappyDataInc/snappydata#901]
[TRACE 2017/11/28 13:57:01.786 IST GFXD:error:FabricServiceAPI <main> tid=0x1] XJ040 error occurred while starting server : java.sql.SQLException(XJ040): Failed to start database 'gemfirexd', see the cause for details.
Exception in thread "main" java.sql.SQLException(XJ040): Failed to start database 'gemfirexd', see the cause for details.
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedSQLException.wrapStandardException(EmbedSQLException.java:158)
	at com.pivotal.gemfirexd.internal.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:734)
	at com.pivotal.gemfirexd.internal.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:664)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:3001)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:709)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection30.<init>(EmbedConnection30.java:94)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection40.<init>(EmbedConnection40.java:75)
	at com.pivotal.gemfirexd.internal.jdbc.Driver40.getNewEmbedConnection(Driver40.java:95)
	at com.pivotal.gemfirexd.internal.jdbc.InternalDriver.connect(InternalDriver.java:351)
	at com.pivotal.gemfirexd.internal.jdbc.InternalDriver.connect(InternalDriver.java:219)
	at com.pivotal.gemfirexd.internal.jdbc.InternalDriver.connect(InternalDriver.java:195)
	at io.snappydata.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:153)
	at com.pivotal.gemfirexd.internal.engine.fabricservice.FabricServiceImpl.startImpl(FabricServiceImpl.java:279)
	at com.pivotal.gemfirexd.internal.engine.fabricservice.FabricServerImpl.start(FabricServerImpl.java:60)
	at io.snappydata.impl.ServerImpl.start(ServerImpl.scala:43)
	at io.snappydata.impl.ServerImpl.start(ServerImpl.scala:38)
	at io.snappydata.util.ServiceUtils$.invokeStartFabricServer(ServiceUtils.scala:87)
	at org.apache.spark.sql.SnappyContext$.invokeServices(SnappyContext.scala:1116)
	at org.apache.spark.sql.SnappyContext$.initGlobalSnappyContext(SnappyContext.scala:1082)
	at org.apache.spark.sql.SnappySession.<init>(SnappySession.scala:132)
	at org.apache.spark.sql.SnappySession.<init>(SnappySession.scala:83)
	at spk.Dfg.main(Dfg.java:40)
Caused by: ERROR XJ040: Failed to start database 'gemfirexd', see the cause for details.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.postCreate(FabricDatabase.java:587)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:659)
	... 17 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: HADOOPFS
	at com.pivotal.gemfirexd.internal.engine.store.GemFireStore.initExternalCatalog(GemFireStore.java:2373)
	at com.pivotal.gemfirexd.internal.engine.db.FabricDatabase.postCreate(FabricDatabase.java:540)
	... 18 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: HADOOPFS
	at io.snappydata.impl.SnappyHiveCatalog.<init>(SnappyHiveCatalog.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.pivotal.gemfirexd.internal.engine.store.GemFireStore.initExternalCatalog(GemFireStore.java:2359)
	... 19 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: HADOOPFS
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.snappydata.impl.SnappyHiveCatalog.<init>(SnappyHiveCatalog.java:85)
	... 25 more
Caused by: java.lang.NoSuchFieldError: HADOOPFS
	at io.snappydata.impl.SnappyHiveCatalog.initCommonHiveMetaStoreProperties(SnappyHiveCatalog.java:130)
	at io.snappydata.impl.SnappyHiveCatalog$HMSQuery.initHMC(SnappyHiveCatalog.java:462)
	at io.snappydata.impl.SnappyHiveCatalog$HMSQuery.call(SnappyHiveCatalog.java:300)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sumwale** [comment]
@yashwanth2804 Looks like there are multiple hive libraries in the classpath of server. Can you paste the contents of server log file (in work/localhost-server-1 by default) and the classpath entries that are printed at the top?
