### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope

### ISSUE THREAD

**Issue by fire** [SnappyDataInc/snappydata#917]
git @ tested two git commits 88a5bcb012da6e7e59d9dda764c97a891388417a to db469bc4c15afe6e5a181dc2edd4dfb9d14d16d8 which fail

SnappyData using thrift + framed-transport + binary-protocol

Unable to do a `select 1`;

```
SQL Error [30000] [38000]: (SQLState=38000 Severity=30000) (Server=snappydata-server-0.snappydata-server.myproject.svc.cluster.local/172.17.0.4[1527] Thread=ThriftProcessor-0) The exception 'com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 172.17.0.4(16)<v21>:56171, caused by com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$' was thrown while evaluating an expression.
  (SQLState=38000 Severity=30000) (Server=snappydata-server-0.snappydata-server.myproject.svc.cluster.local/172.17.0.4[1527] Thread=ThriftProcessor-0) The exception 'com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 172.17.0.4(16)<v21>:56171, caused by com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$' was thrown while evaluating an expression.
    Server STACK: java.sql.SQLException(38000): The exception 'com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 172.17.0.4(16)<v21>:56171, caused by com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$' was thrown while evaluating an expression.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.engine.Misc.processFunctionException(Misc.java:839)
	at com.pivotal.gemfirexd.internal.engine.Misc.processFunctionException(Misc.java:784)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappySelectResultSet.setup(SnappySelectResultSet.java:286)
	at com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.executeFunction(GfxdFunctionMessage.java:332)
	at com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.executeFunction(GfxdFunctionMessage.java:274)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.executeOnLeadNode(SnappyActivation.java:331)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.executeWithResultSet(SnappyActivation.java:194)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.execute(SnappyActivation.java:150)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericActivationHolder.execute(GenericActivationHolder.java:462)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:586)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2175)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1289)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1006)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:972)
	at io.snappydata.thrift.server.SnappyDataServiceImpl.execute(SnappyDataServiceImpl.java:1697)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1511)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1495)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at io.snappydata.thrift.server.SnappyDataServiceImpl$Processor.process(SnappyDataServiceImpl.java:200)
	at io.snappydata.thrift.server.SnappyThriftServerThreadPool$WorkerProcess.run(SnappyThriftServerThreadPool.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.snappydata.thrift.server.SnappyThriftServer$1.lambda$newThread$0(SnappyThriftServer.java:143)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 172.17.0.4(16)<v21>:56171, caused by com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector$Itr.moveNext(GfxdQueryStreamingResultCollector.java:451)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector$Itr.<init>(GfxdQueryStreamingResultCollector.java:363)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector.iterator(GfxdQueryStreamingResultCollector.java:207)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappySelectResultSet.setup(SnappySelectResultSet.java:280)
	... 21 more
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4880)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$.getPlan(SnappySession.scala:2174)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anonfun$sql$1.apply(SnappySession.scala:176)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anonfun$sql$1.apply(SnappySession.scala:176)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.aqp.SnappyContextFunctions.sql(SnappyContextFunctions.scala:91)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession.sql(SnappySession.scala:176)
	at Remote Member '172.17.0.3(14)<v20>:44594' in io.snappydata.gemxd.SparkSQLExecuteImpl.<init>(SparkSQLExecuteImpl.scala:79)
	at Remote Member '172.17.0.3(14)<v20>:44594' in io.snappydata.gemxd.ClusterCallbacksImpl$.getSQLExecute(ClusterCallbacksImpl.scala:88)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.pivotal.gemfirexd.internal.engine.distributed.message.LeadNodeExecutorMsg.execute(LeadNodeExecutorMsg.java:142)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.processMessage(GfxdFunctionMessage.java:739)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.basicProcess(GfxdMessage.java:406)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.internal.cache.AbstractOperationMessage.process(AbstractOperationMessage.java:221)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:431)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:503)
	at Remote Member '172.17.0.3(14)<v20>:44594' in java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at Remote Member '172.17.0.3(14)<v20>:44594' in java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:733)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionManager$9$1.run(DistributionManager.java:1181)
	at Remote Member '172.17.0.3(14)<v20>:44594' in java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.SparkContext.withScope(SparkContext.scala:727)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.SparkContext.parallelize(SparkContext.scala:741)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.SparkStrategies.singleRowRdd$lzycompute(SparkStrategies.scala:297)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.SparkStrategies.singleRowRdd(SparkStrategies.scala:297)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:406)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:77)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:66)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:77)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:66)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$.org$apache$spark$sql$SnappySession$$evaluatePlan(SnappySession.scala:1927)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anon$3.load(SnappySession.scala:2071)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anon$3.load(SnappySession.scala:2064)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
	... 22 more

    Server STACK: java.sql.SQLException(38000): The exception 'com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 172.17.0.4(16)<v21>:56171, caused by com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$' was thrown while evaluating an expression.
	at com.pivotal.gemfirexd.internal.iapi.error.StandardException.newException(StandardException.java:473)
	at com.pivotal.gemfirexd.internal.engine.Misc.processFunctionException(Misc.java:839)
	at com.pivotal.gemfirexd.internal.engine.Misc.processFunctionException(Misc.java:784)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappySelectResultSet.setup(SnappySelectResultSet.java:286)
	at com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.executeFunction(GfxdFunctionMessage.java:332)
	at com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.executeFunction(GfxdFunctionMessage.java:274)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.executeOnLeadNode(SnappyActivation.java:331)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.executeWithResultSet(SnappyActivation.java:194)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappyActivation.execute(SnappyActivation.java:150)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericActivationHolder.execute(GenericActivationHolder.java:462)
	at com.pivotal.gemfirexd.internal.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:586)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:2175)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1289)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:1006)
	at com.pivotal.gemfirexd.internal.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:972)
	at io.snappydata.thrift.server.SnappyDataServiceImpl.execute(SnappyDataServiceImpl.java:1697)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1511)
	at io.snappydata.thrift.SnappyDataService$Processor$execute.getResult(SnappyDataService.java:1495)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at io.snappydata.thrift.server.SnappyDataServiceImpl$Processor.process(SnappyDataServiceImpl.java:200)
	at io.snappydata.thrift.server.SnappyThriftServerThreadPool$WorkerProcess.run(SnappyThriftServerThreadPool.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.snappydata.thrift.server.SnappyThriftServer$1.lambda$newThread$0(SnappyThriftServer.java:143)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.pivotal.gemfirexd.internal.engine.jdbc.GemFireXDRuntimeException: myID: 172.17.0.4(16)<v21>:56171, caused by com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector$Itr.moveNext(GfxdQueryStreamingResultCollector.java:451)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector$Itr.<init>(GfxdQueryStreamingResultCollector.java:363)
	at com.pivotal.gemfirexd.internal.engine.distributed.GfxdQueryStreamingResultCollector.iterator(GfxdQueryStreamingResultCollector.java:207)
	at com.pivotal.gemfirexd.internal.engine.sql.execute.SnappySelectResultSet.setup(SnappySelectResultSet.java:280)
	... 21 more
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2261)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4880)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$.getPlan(SnappySession.scala:2174)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anonfun$sql$1.apply(SnappySession.scala:176)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anonfun$sql$1.apply(SnappySession.scala:176)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.aqp.SnappyContextFunctions.sql(SnappyContextFunctions.scala:91)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession.sql(SnappySession.scala:176)
	at Remote Member '172.17.0.3(14)<v20>:44594' in io.snappydata.gemxd.SparkSQLExecuteImpl.<init>(SparkSQLExecuteImpl.scala:79)
	at Remote Member '172.17.0.3(14)<v20>:44594' in io.snappydata.gemxd.ClusterCallbacksImpl$.getSQLExecute(ClusterCallbacksImpl.scala:88)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.pivotal.gemfirexd.internal.engine.distributed.message.LeadNodeExecutorMsg.execute(LeadNodeExecutorMsg.java:142)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.pivotal.gemfirexd.internal.engine.distributed.message.GfxdFunctionMessage.processMessage(GfxdFunctionMessage.java:739)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.pivotal.gemfirexd.internal.engine.distributed.GfxdMessage.basicProcess(GfxdMessage.java:406)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.internal.cache.AbstractOperationMessage.process(AbstractOperationMessage.java:221)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:431)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:503)
	at Remote Member '172.17.0.3(14)<v20>:44594' in java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at Remote Member '172.17.0.3(14)<v20>:44594' in java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:733)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.gemstone.gemfire.distributed.internal.DistributionManager$9$1.run(DistributionManager.java:1181)
	at Remote Member '172.17.0.3(14)<v20>:44594' in java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.SparkContext.withScope(SparkContext.scala:727)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.SparkContext.parallelize(SparkContext.scala:741)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.SparkStrategies.singleRowRdd$lzycompute(SparkStrategies.scala:297)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.SparkStrategies.singleRowRdd(SparkStrategies.scala:297)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.SparkStrategies$BasicOperators$.apply(SparkStrategies.scala:406)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:77)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:66)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:77)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:74)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:66)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at Remote Member '172.17.0.3(14)<v20>:44594' in scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$.org$apache$spark$sql$SnappySession$$evaluatePlan(SnappySession.scala:1927)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anon$3.load(SnappySession.scala:2071)
	at Remote Member '172.17.0.3(14)<v20>:44594' in org.apache.spark.sql.SnappySession$$anon$3.load(SnappySession.scala:2064)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at Remote Member '172.17.0.3(14)<v20>:44594' in com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
	... 22 more
```

**Comment by sumwale** [comment]
Strange one, looks like some ClassLoader issue. You are testing with a clean build? Will check it out but this doesn't have any relation with framed-transport rather something else went bad in build or something.

**Comment by fire** [comment]
Is there any data I can give to help solve this?

**Comment by fire** [comment]
I was importing alluxio 1.6 and I think its jackson library was incompatible.

**Comment by fire** [comment]
Can you recommend a method of including the zeppelin libraries and alluxio that's outside of the snappydata/jars folder?

It won't solve this problem, but would help iteration times I didn't need to rebuild the docker image, yet be able to load from a data directory.

**Comment by sumwale** [comment]
@fire Did you find a way of including the jars cleanly? Like the zeppelin page recommends, the preferred way is using "-classpath .." in conf/leads and servers rather than placing in jars directory that can clash with product jars. The -classpath jars uses a separate ClassLoader so should work for alluxio too. Or else try the SQLJ.INSTALL_JAR (https://snappydatainc.github.io/snappydata/programming_guide/managing_jar_files/) but that one will not make those jars available for arbitrary operations rather only for store ones.
