### ISSUE TITLE
Query error when I use the where expression by snappy-sql

### ISSUE THREAD

**Issue by alexBaiJW** [SnappyDataInc/snappydata#982]
> snappy-sql> select KEY from APP.HOTELEVENTS where EHOTEL_XM="冯早早";
> 错误 38000：(SQLState=38000 Severity=20000) (Server=xx/xx[1527] Thread=ThriftProcessor-52) 求值表达式时抛出异常“cannot resolve '`冯早早`' given input columns: [EHOTEL_XZ, RZSJ, LDDM, EHOTEL_XM, EHOTEL_FJH, EHOTEL_ZJLXDM, KEY_LABEL_1, EHOTEL_HYLX, EHOTEL_SSXMC, KEY, EHOTEL_QTSCSJ, EHOTEL_LKID, EHOTEL_LDMC, EHOTEL_TFSJ, EHOTEL_LDXZ, TYPE, EHOTEL_GXDWMC, KEY_LABEL_2];;
> 'Project ['KEY]
> +- 'Filter (EHOTEL_XM#14694 = '冯早早)
>    +- SubqueryAlias HOTELEVENTS
>       +- Relation[KEY_LABEL_1#14689,EHOTEL_QTSCSJ#14690,RZSJ#14691,EHOTEL_SSXMC#14692,EHOTEL_TFSJ#14693,EHOTEL_XM#14694,EHOTEL_XZ#14695,EHOTEL_ZJLXDM#14696,EHOTEL_FJH#14697,KEY#14698,EHOTEL_LKID#14699,EHOTEL_GXDWMC#14700,EHOTEL_HYLX#14701,KEY_LABEL_2#14702,LDDM#14703,EHOTEL_LDMC#14704,EHOTEL_LDXZ#14705,TYPE#14706] ColumnFormatRelation[APP.HOTELEVENTS]
> ”。

As the above description, does it mean the column name is '冯早早' but not EHOTEL_XM?  Without the where expression, everything goes well.  And I also tried like "where EHOTEL_XM='冯早早'", "EHOTEL_XZ"='冯早早', and so on.  Is there anything wrong with the sql above?  Other error message I met such as the following description:

> 错误 38000：(SQLState=38000 Severity=20000) (Server=xx/xx[1527] Thread=ThriftProcessor-52) 求值表达式时抛出异常“Job aborted due to stage failure: Task 7 in stage 92.0 failed 4 times, most recent failure: Lost task 7.3 in stage 92.0 (TID 6340, xx, executor xx(10466):64535): com.gemstone.gemfire.InternalGemFireError: Bucket com.gemstone.gemfire.internal.cache.BucketRegion[path='/__PR/_B__APP_SNAPPYSYS__INTERNAL________HOTELEVENTS__COLUMN__STORE___106';scope=DISTRIBUTED_ACK';dataPolicy=PERSISTENT_REPLICATE; concurrencyChecksEnabled; indexUpdater=null; serial=1006; primary=true] size (-1330144) negative after applying delta of 1704
> 	at com.gemstone.gemfire.internal.cache.BucketRegion.updateBucketMemoryStats(BucketRegion.java:3115)
> 	at com.gemstone.gemfire.internal.cache.BucketRegion.updateMemoryStats(BucketRegion.java:3094)
> 	at com.gemstone.gemfire.internal.cache.AbstractRegionEntry._setValue(AbstractRegionEntry.java:1447)
> 	at com.gemstone.gemfire.internal.cache.AbstractDiskRegionEntry.setValueWithContext(AbstractDiskRegionEntry.java:61)
> 	at com.gemstone.gemfire.internal.cache.DiskEntry$Helper.setValueOnFaultIn(DiskEntry.java:1425)
> 	at com.gemstone.gemfire.internal.cache.DiskEntry$Helper.readValueFromDisk(DiskEntry.java:1376)
> 	at com.gemstone.gemfire.internal.cache.DiskEntry$Helper.faultInValue(DiskEntry.java:1214)
> 	at com.gemstone.gemfire.internal.cache.AbstractOplogDiskRegionEntry.getValue(AbstractOplogDiskRegionEntry.java:99)
> 	at org.apache.spark.sql.execution.columnar.impl.DiskMultiColumnBatch.entryMap$lzycompute(ColumnFormatIterator.scala:330)
> 	at org.apache.spark.sql.execution.columnar.impl.DiskMultiColumnBatch.entryMap(ColumnFormatIterator.scala:319)
> 	at org.apache.spark.sql.execution.columnar.impl.ColumnFormatIterator.getColumnValue(ColumnFormatIterator.scala:173)
> 	at org.apache.spark.sql.execution.columnar.ColumnBatchIterator.getColumnBuffer(ColumnBatch.scala:186)
> 	at org.apache.spark.sql.execution.columnar.ColumnBatchIterator.moveNext(ColumnBatch.scala:294)
> 	at org.apache.spark.sql.execution.row.PRValuesIterator.hasNext(RowFormatScanRDD.scala:448)
> 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.scan_nextBatch$(generated.java:157)
> 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(generated.java:586)
> 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
> 	at org.apache.spark.sql.execution.WholeStageCodegenRDD$$anon$2.hasNext(WholeStageCodegenExec.scala:571)
> 	at org.apache.spark.sql.execution.WholeStageCodegenRDD$$anon$1.hasNext(WholeStageCodegenExec.scala:508)
> 	at org.apache.spark.sql.CachedDataFrame$.apply(CachedDataFrame.scala:461)
> 	at org.apache.spark.sql.CachedDataFrame$.apply(CachedDataFrame.scala:419)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:95)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:126)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:326)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.apache.spark.executor.SnappyExecutor$$anon$2$$anon$3.run(SnappyExecutor.scala:57)
> 	at java.lang.Thread.run(Thread.java:745)
> 
>

**Comment by alexBaiJW** [comment]
Year, you are right. SQLs as the followings:

> select * from HOTELEVENTS where EHOTEL_FJH='634' limit 10;
select * from HOTELEVENTS where EHOTEL_XM='冯早早' limit 10;
select * from HOTELEVENTS where EHOTEL_XM='冯早早' and EHOTEL_FJH='634' limit 10;

The first two runs correctly, but the third faild. Does this is also reported elsewhere too?

**Comment by alexBaiJW** [comment]
For the following sql, when I first run, it goes error which message is just like the above description(second one). But when I run it again a minute later, it runs correctly. 
> select * from HOTELEVENTS where EHOTEL_XM='冯早早' and EHOTEL_FJH=634 limit 10;
Hope this can do some help to fix it.
