### ISSUE TITLE
Create a column table failed from an external table stored on HDFS

### ISSUE THREAD

**Issue by alexBaiJW** [SnappyDataInc/snappydata#992]
When I create a column table from an external table(which has 84 columns and has 282,567,549 records)which stored on HDFS, I met the errors as follows（if I just select 40,000,000 records, it runs ok:CREATE TABLE p4y using column options() as (select * from p4y limit 40000000);

snappy-sql> CREATE TABLE p4y using column options() as (select * from p40000);
错误 38000：(SQLState=38000 Severity=20000) (Server=xx/xx[1528] Thread=ThriftProcessor-30) 求值表达式时抛出异常“Job aborted due to stage failure: Task 149 in stage 271.0 failed 4 times, most recent failure: Lost task 149.3 in stage 271.0 (TID 11592, xxx, executor xx(10466):64535): com.gemstone.gemfire.InternalGemFireError: Bucket com.gemstone.gemfire.internal.cache.BucketRegion[path='/__PR/_B__APP_SNAPPYSYS__INTERNAL________P40W__COLUMN__STORE___101';scope=DISTRIBUTED_ACK';dataPolicy=PERSISTENT_REPLICATE; concurrencyChecksEnabled; indexUpdater=null; serial=1659; primary=true] size (-2989984) negative after applying delta of -124592
	at com.gemstone.gemfire.internal.cache.BucketRegion.updateBucketMemoryStats(BucketRegion.java:3115)
	at com.gemstone.gemfire.internal.cache.BucketRegion.updateMemoryStats(BucketRegion.java:3094)
	at com.gemstone.gemfire.internal.cache.AbstractRegionEntry._setValue(AbstractRegionEntry.java:1432)
	at com.gemstone.gemfire.internal.cache.AbstractDiskRegionEntry.setValueWithContext(AbstractDiskRegionEntry.java:61)
	at com.gemstone.gemfire.internal.cache.DiskEntry$Helper.overflowToDisk(DiskEntry.java:1569)
	at com.gemstone.gemfire.internal.cache.AbstractLRURegionMap.evictEntry(AbstractLRURegionMap.java:340)
	at com.gemstone.gemfire.internal.cache.AbstractLRURegionMap.centralizedLruUpdateCallback(AbstractLRURegionMap.java:731)
	at org.apache.spark.memory.SnappyStorageEvictor$$anonfun$evictRegionData$1.apply(SnappyStorageEvictor.scala:87)
	at org.apache.spark.memory.SnappyStorageEvictor$$anonfun$evictRegionData$1.apply(SnappyStorageEvictor.scala:83)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at org.apache.spark.memory.SnappyStorageEvictor.evictRegionData(SnappyStorageEvictor.scala:83)
	at org.apache.spark.memory.SnappyUnifiedMemoryManager.askStoragePool_(SnappyUnifiedMemoryManager.scala:636)
	at org.apache.spark.memory.SnappyUnifiedMemoryManager.org$apache$spark$memory$SnappyUnifiedMemoryManager$$askStoragePool(SnappyUnifiedMemoryManager.scala:525)
	at org.apache.spark.memory.SnappyUnifiedMemoryManager.acquireStorageMemoryForObject(SnappyUnifiedMemoryManager.scala:696)
	at org.apache.spark.sql.execution.columnar.impl.StoreCallbacksImpl$.acquireStorageMemory(StoreCallbacksImpl.scala:299)
	at com.gemstone.gemfire.internal.cache.LocalRegion.acquirePoolMemory(LocalRegion.java:14520)
	at com.gemstone.gemfire.internal.cache.EntryEventImpl.acquireMemory(EntryEventImpl.java:1837)
	at com.gemstone.gemfire.internal.cache.EntryEventImpl.setNewValueInRegion(EntryEventImpl.java:1943)
	at com.gemstone.gemfire.internal.cache.EntryEventImpl.putNewEntry(EntryEventImpl.java:1812)
	at com.gemstone.gemfire.internal.cache.AbstractRegionMap.createEntry(AbstractRegionMap.java:4280)
	at com.gemstone.gemfire.internal.cache.AbstractRegionMap.basicPut(AbstractRegionMap.java:4002)
	at com.gemstone.gemfire.internal.cache.AbstractLRURegionMap.basicPut(AbstractLRURegionMap.java:54)
	at com.gemstone.gemfire.internal.cache.BucketRegion.virtualPut(BucketRegion.java:712)
	at com.gemstone.gemfire.internal.cache.PartitionedRegionDataStore.putLocally(PartitionedRegionDataStore.java:1362)
	at com.gemstone.gemfire.internal.cache.PartitionedRegionDataStore.putLocally(PartitionedRegionDataStore.java:1337)
	at com.gemstone.gemfire.internal.cache.PartitionedRegionDataView.putEntryOnRemote(PartitionedRegionDataView.java:116)
	at com.gemstone.gemfire.internal.cache.partitioned.PutAllPRMessage.doLocalPutAll(PutAllPRMessage.java:560)
	at com.gemstone.gemfire.internal.cache.PartitionedRegion.tryToSendOnePutAllMessage(PartitionedRegion.java:3045)
	at com.gemstone.gemfire.internal.cache.PartitionedRegion.sendOrWaitForRespWithRetry(PartitionedRegion.java:2872)
	at com.gemstone.gemfire.internal.cache.PartitionedRegion.sendMsgByBucket(PartitionedRegion.java:2757)
	at com.gemstone.gemfire.internal.cache.PartitionedRegion.access$100(PartitionedRegion.java:239)
	at com.gemstone.gemfire.internal.cache.PartitionedRegion$8.execute(PartitionedRegion.java:2423)
	at com.gemstone.gnu.trove.THashMap.forEachEntry(THashMap.java:309)
	at com.gemstone.gemfire.internal.cache.PartitionedRegion.postPutAllSend(PartitionedRegion.java:2415)
	at com.gemstone.gemfire.internal.cache.LocalRegionDataView.postPutAll(LocalRegionDataView.java:406)
	at com.gemstone.gemfire.internal.cache.TXStateProxy.postPutAll(TXStateProxy.java:3843)
	at com.gemstone.gemfire.internal.cache.LocalRegion.basicPutAll(LocalRegion.java:11846)
	at org.apache.spark.sql.execution.columnar.impl.JDBCSourceAsColumnarStore.doSnappyInsertOrPut(JDBCSourceAsColumnarStore.scala:402)
	at org.apache.spark.sql.execution.columnar.impl.JDBCSourceAsColumnarStore.doInsertOrPut(JDBCSourceAsColumnarStore.scala:573)
	at org.apache.spark.sql.execution.columnar.impl.JDBCSourceAsColumnarStore.storeColumnBatch(JDBCSourceAsColumnarStore.scala:99)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.columninsert_storeColumnBatch$(generated.java:3020)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(generated.java:5042)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenRDD$$anon$2.hasNext(WholeStageCodegenExec.scala:571)
	at org.apache.spark.sql.execution.WholeStageCodegenRDD$$anon$1.hasNext(WholeStageCodegenExec.scala:508)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:231)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:828)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:828)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:41)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:95)
	at org.apache.spark.scheduler.Task.run(Task.scala:126)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:326)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.spark.executor.SnappyExecutor$$anon$2$$anon$3.run(SnappyExecutor.scala:57)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sumwale** [comment]
@alexBaiJW This is the same issue reported in #988 . We are looking into these.
