### ISSUE TITLE
snappysession  both delete() or sql() API can't remove columnar rows

### ISSUE THREAD

**Issue by crabo** [SnappyDataInc/snappydata#997]
I have a column table , type in snappy-sql:
snappy-sql> delete from ys_send where BatchNO in (572365);
    4 rows inserted/updated/deleted

------------
Option 1:    snappy.sql("delete from ys_send where BatchNO in (572365)") ;
code hangs here,for more than 1 minutes, no further results.

Option2:  snappy.delete("ys_send","BatchNO IN (572365)");
Exception throws:
org.apache.spark.sql.AnalysisException: ys_send is not a deletable table;
        at org.apache.spark.sql.SnappySession.delete(SnappySession.scala:1751) 
        at com.nas.writer.snappywriter.SnappyWriter$Task.doDelete(SnappyWriter.java:260) 

Thanks in advance!

**Comment by sumwale** [comment]
@crabo How much time the delete from snappy-sql shell takes?

For single value you may want to use "BatchNo = ..." instead of IN which should be faster. Can you check the GUI plan in the SQL tab for Option 1 above and attach a screenshot? It should have been identical to snappy-sql delete.

Option 2 is meant only for row tables. A separate API for column tables will be added soon.

Option 3 only replaces existing rows if the table has "key_columns" defined as the BatchNo column during table creation.

**Comment by crabo** [comment]
Hi,there. glad to hear you.
Option 1 I have about 1k keys in a batch. in api mode it hangs stop there. jdbc mode and sql shell execute quite fast, less than a second.

Option 2 still in progress,wait for next version ha?

Option 3 ,I already used key_colums in the column table,but rows gets append never overwritten.

Now, I switch to whole jdbc connection process, delete than insert into become my finnal solution. It writes about 10MB/s , only 1/5 ingest speed to the previous Dataframe api insert()

thanks for your geat works!
